"""Artifact schema registry for local platform outputs."""

from __future__ import annotations

from fnmatch import fnmatch
from pathlib import Path

from .models import ArtifactSchemaDefinition


def _definition(
    artifact_type: str,
    required: list[str],
    patterns: list[str],
    kind: str = "json",
    optional: list[str] | None = None,
    allow_empty: bool = True,
) -> ArtifactSchemaDefinition:
    return ArtifactSchemaDefinition(
        artifact_type=artifact_type,
        schema_version="1.0",
        required_fields=required,
        optional_fields=optional or [
            "artifact_type",
            "schema_version",
            "producer",
            "created_at",
            "artifact_metadata",
        ],
        file_patterns=patterns,
        json_or_jsonl=kind,
        allow_empty=allow_empty,
    )


ARTIFACT_SCHEMA_REGISTRY: dict[str, ArtifactSchemaDefinition] = {
    "research_suite_result": _definition("research_suite_result", ["suite_name", "status", "stages"], ["suite_result.json"]),
    "artifact_catalog": _definition("artifact_catalog", ["suite_name", "created_at", "entries"], ["artifact_catalog.json"]),
    "promotion_decision": _definition("promotion_decision", [], ["promotion_decision.json"]),
    "data_source_smoke_report": _definition("data_source_smoke_report", ["provider", "status", "datasets"], ["data_source_smoke_report.json"]),
    "provider_probe": _definition("provider_probe", ["probes"], ["provider_probe.json"]),
    "field_coverage": _definition("field_coverage", ["datasets"], ["field_coverage.json"]),
    "audit_summary": _definition("audit_summary", [], ["audit_summary.json"]),
    "incremental_recovery_report": _definition("incremental_recovery_report", [], ["incremental_recovery_report.json"]),
    "baseline_compare_summary": _definition("baseline_compare_summary", [], ["baseline_compare_summary.json"]),
    "dataset_contracts": _definition("dataset_contracts", ["datasets"], ["dataset_contracts.json"]),
    "backfill_plan": _definition("backfill_plan", ["plan_id", "scope", "jobs"], ["backfill_plan.json"]),
    "backfill_state": _definition("backfill_state", ["plan_id", "jobs"], ["backfill_state.json"]),
    "backfill_run_report": _definition("backfill_run_report", ["plan_id", "provider", "status", "jobs"], ["backfill_run_report.json"]),
    "backfill_job_results": _definition("backfill_job_results", ["job_id", "dataset", "status"], ["backfill_job_results.jsonl"], kind="jsonl", allow_empty=True),
    "backfill_job_result": _definition("backfill_job_result", ["job_id", "dataset"], ["job_result.json"]),
    "backfill_staging_records": _definition("backfill_staging_records", [], ["staging/jobs/*/*/records.jsonl"], kind="jsonl", allow_empty=True),
    "backfill_quota_summary": _definition("backfill_quota_summary", ["provider", "status", "estimated_requests"], ["backfill_quota_summary.json"]),
    "backfill_readiness_report": _definition("backfill_readiness_report", ["provider", "status", "quota"], ["backfill_readiness_report.json"]),
    "backfill_coverage_report": _definition("backfill_coverage_report", ["datasets", "gap_count", "status"], ["backfill_coverage_report.json"]),
    "backfill_coverage_matrix": _definition("backfill_coverage_matrix", ["records", "gap_count"], ["backfill_coverage_matrix.json"]),
    "backfill_coverage_gaps": _definition("backfill_coverage_gaps", ["dataset", "gap"], ["backfill_coverage_gaps.jsonl"], kind="jsonl", allow_empty=True),
    "dataset_version_manifest": _definition("dataset_version_manifest", ["dataset_version_id", "dataset_fingerprints", "content_hash"], ["dataset_version_manifest.json"]),
    "dataset_versions": _definition("dataset_versions", ["dataset_version_id", "content_hash"], ["dataset_versions.jsonl"], kind="jsonl", allow_empty=True),
    "data_lake_registry": _definition("data_lake_registry", ["dataset_versions", "research_freezes"], ["data_lake_registry.json"]),
    "research_data_freeze": _definition("research_data_freeze", ["freeze_id", "dataset_version_id", "content_hash"], ["research_data_freeze.json"]),
    "research_freezes": _definition("research_freezes", ["freeze_id", "dataset_version_id"], ["research_freezes.jsonl"], kind="jsonl", allow_empty=True),
    "freeze_manifest": _definition("freeze_manifest", ["freeze_id", "dataset_version_id", "content_hash", "files"], ["freeze_manifest.json"]),
    "freeze_validation_report": _definition("freeze_validation_report", ["freeze_dir", "status", "error_count"], ["freeze_validation_report.json"]),
    "data_lake_events": _definition("data_lake_events", ["event_type", "target_id"], ["data_lake_events.jsonl"], kind="jsonl", allow_empty=True),
    "data_lake_report": _definition("data_lake_report", ["registry_dir", "versions", "freezes"], ["data_lake_report.json"]),
    "data_lineage_graph": _definition("data_lineage_graph", ["nodes", "edges"], ["data_lineage_graph.json"]),
    "data_retention_report": _definition("data_retention_report", ["freeze_count", "total_size_bytes", "retired_freezes"], ["data_retention_report.json"]),
    "matrix_version_manifest": _definition("matrix_version_manifest", ["fields", "n_stocks", "n_dates"], ["matrix_version_manifest.json"]),
    "compute_resource_snapshot": _definition("compute_resource_snapshot", ["captured_at", "devices"], ["compute_resource_snapshot.json"]),
    "compute_run_report": _definition("compute_run_report", ["run_id", "status", "job_count"], ["compute_run_report.json"]),
    "compute_jobs": _definition("compute_jobs", ["job_id", "job_kind"], ["compute_jobs.jsonl"], kind="jsonl", allow_empty=True),
    "compute_jobs_manifest": _definition("compute_jobs_manifest", ["jobs"], ["compute_jobs.json"]),
    "compute_job_runs": _definition("compute_job_runs", ["job_id", "status"], ["compute_job_runs.jsonl"], kind="jsonl", allow_empty=True),
    "compute_job_run": _definition("compute_job_run", ["job_id", "status"], ["compute_job_run_*.json"]),
    "compute_scheduler_events": _definition("compute_scheduler_events", ["event_type"], ["compute_scheduler_events.jsonl"], kind="jsonl", allow_empty=True),
    "compute_heartbeats": _definition("compute_heartbeats", ["job_id", "status"], ["compute_heartbeats.jsonl"], kind="jsonl", allow_empty=True),
    "gpu_leases": _definition("gpu_leases", ["lease_id"], ["gpu_leases.jsonl"], kind="jsonl", allow_empty=True),
    "experiment_plan": _definition("experiment_plan", ["experiment_id", "workflow", "compute_jobs"], ["experiment_plan.json"]),
    "experiment_graph": _definition("experiment_graph", ["nodes", "edges"], ["experiment_graph.json"]),
    "experiment_run_report": _definition("experiment_run_report", ["experiment_id", "workflow", "status"], ["experiment_run_report.json"]),
    "experiment_resource_plan": _definition("experiment_resource_plan", ["shard_count"], ["experiment_resource_plan.json"]),
    "experiment_shards": _definition("experiment_shards", ["shard_id", "shard_count"], ["experiment_shards.jsonl"], kind="jsonl", allow_empty=True),
    "experiment_shard_manifest": _definition("experiment_shard_manifest", ["shard_id", "shard_hash"], ["shard_manifest.json"]),
    "experiment_merge_report": _definition("experiment_merge_report", ["status", "shard_count"], ["experiment_merge_report.json"]),
    "experiment_artifact_catalog": _definition("experiment_artifact_catalog", ["experiment_id", "entries"], ["experiment_artifact_catalog.json"]),
    "distributed_training_report": _definition("distributed_training_report", ["distributed", "world_size"], ["distributed_training_report.json"]),
    "resource_usage_report": _definition("resource_usage_report", [], ["resource_usage.json"]),
    "gpu_benchmark_report": _definition("gpu_benchmark_report", [], ["benchmark_result.json", "merged_benchmark_result.json"]),
    "capacity_report": _definition("capacity_report", ["trade_date", "config", "portfolio"], ["capacity_report.json"]),
    "execution_plan": _definition("execution_plan", ["schedule", "fills", "quality"], ["execution_plan.json"]),
    "execution_quality": _definition("execution_quality", ["execution_fill_rate"], ["execution_quality.json"]),
    "parent_orders": _definition("parent_orders", ["parent_order_id"], ["parent_orders.jsonl"], kind="jsonl", allow_empty=True),
    "child_orders": _definition("child_orders", ["child_order_id"], ["child_orders.jsonl"], kind="jsonl", allow_empty=True),
    "child_fills": _definition("child_fills", ["trade_date", "ts_code", "status"], ["child_fills.jsonl"], kind="jsonl", allow_empty=True),
    "broker_report": _definition("broker_report", ["batch_id", "summary"], ["broker_report.json"]),
    "broker_reconciliation": _definition("broker_reconciliation", [], ["broker_reconciliation.json"]),
    "broker_orders": _definition("broker_orders", ["client_order_id"], ["broker_orders.jsonl"], kind="jsonl", allow_empty=True),
    "broker_events": _definition("broker_events", ["event_id"], ["broker_events.jsonl"], kind="jsonl", allow_empty=True),
    "broker_fills": _definition("broker_fills", ["broker_fill_id"], ["broker_fills.jsonl"], kind="jsonl", allow_empty=True),
    "broker_instruction_manifest": _definition("broker_instruction_manifest", ["batch_id"], ["broker_instruction_manifest.json"]),
    "broker_statement_manifest": _definition("broker_statement_manifest", ["statement_id", "account_id", "schema_name", "record_counts"], ["broker_statement_manifest.json"]),
    "broker_statement_import_report": _definition(
        "broker_statement_import_report",
        ["statement_id", "status", "record_counts", "paths"],
        ["broker_statement_import_report.json"],
    ),
    "broker_statement_parse_issues": _definition("broker_statement_parse_issues", ["severity", "code", "message"], ["broker_statement_parse_issues.jsonl"], kind="jsonl", allow_empty=True),
    "broker_statement_validation_report": _definition("broker_statement_validation_report", ["statement_id", "issues"], ["broker_statement_validation_report.json"]),
    "normalized_external_orders": _definition("normalized_external_orders", ["account_id"], ["normalized_external_orders.jsonl"], kind="jsonl", allow_empty=True),
    "normalized_external_trades": _definition("normalized_external_trades", ["account_id"], ["normalized_external_trades.jsonl"], kind="jsonl", allow_empty=True),
    "normalized_external_fills": _definition("normalized_external_fills", ["account_id"], ["normalized_external_fills.jsonl"], kind="jsonl", allow_empty=True),
    "normalized_external_positions": _definition("normalized_external_positions", ["account_id"], ["normalized_external_positions.jsonl"], kind="jsonl", allow_empty=True),
    "normalized_external_cash": _definition("normalized_external_cash", ["account_id"], ["normalized_external_cash.jsonl"], kind="jsonl", allow_empty=True),
    "normalized_external_settlements": _definition("normalized_external_settlements", ["account_id"], ["normalized_external_settlements.jsonl"], kind="jsonl", allow_empty=True),
    "normalized_external_corporate_actions": _definition("normalized_external_corporate_actions", ["account_id"], ["normalized_external_corporate_actions.jsonl"], kind="jsonl", allow_empty=True),
    "eod_reconciliation_report": _definition("eod_reconciliation_report", ["statement_id", "status", "summary"], ["eod_reconciliation_report.json"]),
    "reconciliation_breaks": _definition("reconciliation_breaks", ["break_id", "break_type", "severity"], ["reconciliation_breaks.jsonl"], kind="jsonl", allow_empty=True),
    "external_account_mirror": _definition("external_account_mirror", ["statement_id", "account_id"], ["external_account_mirror.json"]),
    "external_cash_mirror": _definition("external_cash_mirror", ["account_id"], ["external_cash_mirror.jsonl"], kind="jsonl", allow_empty=True),
    "external_position_mirror": _definition("external_position_mirror", ["account_id"], ["external_position_mirror.jsonl"], kind="jsonl", allow_empty=True),
    "external_fill_mirror": _definition("external_fill_mirror", ["account_id"], ["external_fill_mirror.jsonl"], kind="jsonl", allow_empty=True),
    "external_settlement_mirror": _definition("external_settlement_mirror", ["account_id"], ["external_settlement_mirror.jsonl"], kind="jsonl", allow_empty=True),
    "adjustment_proposals": _definition("adjustment_proposals", ["adjustment_id", "adjustment_type"], ["adjustment_proposals.jsonl"], kind="jsonl", allow_empty=True),
    "adjustment_proposal_batch": _definition("adjustment_proposal_batch", ["adjustment_batch_id", "proposals"], ["adjustment_proposal_batch.json"]),
    "adjustment_application_result": _definition("adjustment_application_result", ["approval_id", "applied_count"], ["adjustment_application_result.json"]),
    "adjustment_ledger": _definition("adjustment_ledger", ["adjustment_id", "approval_id"], ["adjustment_ledger.jsonl"], kind="jsonl", allow_empty=True),
    "monitoring_report": _definition("monitoring_report", ["as_of_date", "checks", "alerts"], ["monitoring_report.json"]),
    "alerts": _definition("alerts", ["severity", "check", "message"], ["alerts.jsonl"], kind="jsonl", allow_empty=True),
    "risk_model_report": _definition("risk_model_report", [], ["risk_model_report.json"]),
    "risk_report": _definition("risk_report", [], ["risk_report.json"]),
    "risk_exposures": _definition("risk_exposures", ["trade_date"], ["risk_exposures.jsonl"], kind="jsonl", allow_empty=True),
    "risk_decomposition": _definition("risk_decomposition", ["trade_date"], ["risk_decomposition.jsonl"], kind="jsonl", allow_empty=True),
    "return_attribution": _definition("return_attribution", ["trade_date"], ["return_attribution.jsonl"], kind="jsonl", allow_empty=True),
    "optimization_result": _definition("optimization_result", [], ["optimization_result.json"]),
    "backtest_result": _definition("backtest_result", ["snapshots", "fills", "metrics"], ["backtest_result.json"]),
    "orders": _definition("orders", ["trade_date", "ts_code", "side"], ["orders.jsonl"], kind="jsonl", allow_empty=True),
    "paper_fills": _definition("paper_fills", ["trade_date", "ts_code", "status"], ["paper_fills.jsonl"], kind="jsonl", allow_empty=True),
    "production_run": _definition("production_run", ["run_id", "status", "summary"], ["production_run.json"]),
    "approval_batch": _definition("approval_batch", ["approval_id", "status", "orders"], ["approvals/*.json", "*.approval.json"]),
    "paper_account_state": _definition("paper_account_state", ["account_id", "cash", "positions"], ["account_state.json"]),
    "risk_control_policy_manifest": _definition("risk_control_policy_manifest", ["policy_id", "profile"], ["risk_control_policy_manifest.json", "risk_control_policy.json"]),
    "risk_control_state": _definition("risk_control_state", ["kill_switch"], ["risk_control_state.json"]),
    "risk_control_report": _definition("risk_control_report", ["policy_id", "status", "accepted_orders", "rejected_orders"], ["risk_control_report.json"]),
    "risk_control_breaches": _definition("risk_control_breaches", ["breach_id", "limit_id", "severity"], ["risk_control_breaches.jsonl"], kind="jsonl", allow_empty=True),
    "risk_control_decisions": _definition("risk_control_decisions", ["decision_id", "order_id", "status"], ["risk_control_decisions.jsonl"], kind="jsonl", allow_empty=True),
    "risk_limit_usage": _definition("risk_limit_usage", ["usage_id", "metric", "value"], ["risk_limit_usage.jsonl"], kind="jsonl", allow_empty=True),
    "kill_switch_state": _definition("kill_switch_state", ["active"], ["kill_switch_state.json"]),
    "risk_override_request": _definition("risk_override_request", ["override_id", "scope", "status"], ["risk_override_request.json"]),
    "risk_override_records": _definition("risk_override_records", ["override_id", "approval_id", "status"], ["risk_override_records.jsonl"], kind="jsonl", allow_empty=True),
    "risk_accepted_orders": _definition("risk_accepted_orders", ["trade_date", "ts_code", "side"], ["accepted_orders.jsonl"], kind="jsonl", allow_empty=True),
    "risk_rejected_orders": _definition("risk_rejected_orders", ["trade_date", "ts_code", "side"], ["rejected_orders.jsonl"], kind="jsonl", allow_empty=True),
    "risk_clipped_orders": _definition("risk_clipped_orders", ["trade_date", "ts_code", "side"], ["clipped_orders.jsonl"], kind="jsonl", allow_empty=True),
    "settlement_report": _definition("settlement_report", ["account_id", "as_of_date", "cash_buckets"], ["settlement_report.json"]),
    "settlement_events": _definition("settlement_events", ["settlement_event_id", "account_id", "event_type"], ["settlement_events.jsonl"], kind="jsonl", allow_empty=True),
    "cash_buckets": _definition("cash_buckets", ["trade_date", "total_cash", "available_cash"], ["cash_buckets.jsonl"], kind="jsonl", allow_empty=True),
    "position_lots": _definition("position_lots", ["lot_id", "ts_code", "shares_remaining"], ["position_lots.jsonl"], kind="jsonl", allow_empty=True),
    "position_availability": _definition("position_availability", ["ts_code", "trade_date", "available_shares"], ["position_availability.jsonl"], kind="jsonl", allow_empty=True),
    "realized_pnl": _definition("realized_pnl", ["trade_date", "ts_code", "realized_pnl"], ["realized_pnl.jsonl"], kind="jsonl", allow_empty=True),
    "account_nav": _definition("account_nav", ["trade_date", "equity"], ["account_nav.jsonl"], kind="jsonl", allow_empty=True),
    "account_performance_report": _definition("account_performance_report", [], ["account_performance_report.json"]),
    "account_reconciliation_report": _definition("account_reconciliation_report", ["account_id", "as_of_date"], ["account_reconciliation_report.json"]),
    "fee_tax_report": _definition("fee_tax_report", [], ["fee_tax_report.json"]),
    "corporate_actions_report": _definition("corporate_actions_report", ["event_count", "implemented_action_count"], ["corporate_actions_report.json"]),
    "corporate_action_events": _definition("corporate_action_events", ["action_id", "ts_code", "action_type"], ["corporate_action_events.jsonl"], kind="jsonl", allow_empty=True),
    "corporate_action_schedule": _definition("corporate_action_schedule", ["schedule"], ["corporate_action_schedule.json"]),
    "corporate_action_validation_report": _definition("corporate_action_validation_report", ["event_count", "issues"], ["corporate_action_validation_report.json"]),
    "adjustment_factor_reconciliation": _definition("adjustment_factor_reconciliation", ["issue_count", "issues"], ["adjustment_factor_reconciliation.json"]),
    "total_return_series": _definition("total_return_series", ["trade_date", "ts_code", "total_return_price"], ["total_return_series.jsonl"], kind="jsonl", allow_empty=True),
    "total_return_report": _definition("total_return_report", ["records", "total_return_mode"], ["total_return_report.json"]),
    "corporate_action_ledger": _definition("corporate_action_ledger", ["action_id", "status"], ["corporate_action_ledger.jsonl"], kind="jsonl", allow_empty=True),
    "settlement_ledger": _definition("settlement_ledger", [], ["settlement_ledger.jsonl"], kind="jsonl", allow_empty=True),
    "artifact_schema_manifest": _definition("artifact_schema_manifest", ["entries"], ["artifact_schema_manifest.json"]),
    "artifact_validation_report": _definition("artifact_validation_report", ["results"], ["artifact_validation_report.json"]),
    "release_manifest": _definition("release_manifest", ["release_name", "created_at"], ["release_manifest.json"]),
    "release_gate_report": _definition("release_gate_report", ["checks"], ["release_gate_report.json"]),
    "dependency_inventory": _definition("dependency_inventory", ["files"], ["dependency_inventory.json"]),
    "module_inventory": _definition("module_inventory", ["modules"], ["module_inventory.json"]),
    "cli_inventory": _definition("cli_inventory", ["entries"], ["cli_inventory.json"]),
    "ci_report": _definition("ci_report", ["commands"], ["ci_report.json"]),
    "ci_command_results": _definition("ci_command_results", ["name", "returncode"], ["ci_command_results.jsonl"], kind="jsonl", allow_empty=True),
    "formula_corpus": _definition("formula_corpus", ["formula_hash", "formula_tokens"], ["formula_corpus.jsonl"], kind="jsonl", allow_empty=False),
    "formula_sequences": _definition("formula_sequences", ["formula_hash", "prefix_tokens", "target_token"], ["formula_sequences.jsonl"], kind="jsonl", allow_empty=False),
    "formula_preferences": _definition("formula_preferences", ["pair_id", "preferred_hash", "rejected_hash"], ["formula_preferences.jsonl"], kind="jsonl", allow_empty=True),
    "formula_corpus_stats": _definition("formula_corpus_stats", ["total_records", "valid_records"], ["formula_corpus_stats.json"]),
    "formula_corpus_build_result": _definition("formula_corpus_build_result", ["created_at", "stats", "paths"], ["formula_corpus_build_result.json"]),
    "formula_batch_eval_result": _definition("formula_batch_eval_result", ["batch_id", "results", "summary"], ["formula_batch_eval_result.json"]),
    "formula_eval_results": _definition("formula_eval_results", ["request", "status", "score"], ["formula_eval_results.jsonl"], kind="jsonl", allow_empty=True),
    "formula_eval_cache_manifest": _definition("formula_eval_cache_manifest", ["cache_dir", "enabled"], ["formula_eval_cache_manifest.json"]),
    "formula_batch_eval_benchmark": _definition("formula_batch_eval_benchmark", ["formulas_requested", "elapsed_seconds"], ["formula_batch_eval_benchmark.json"]),
    "formula_eval_shard_manifest": _definition("formula_eval_shard_manifest", ["shard_id", "shard_count", "record_count"], ["shard_manifest.json"]),
    "alphagpt_pretrain_result": _definition("alphagpt_pretrain_result", ["status", "history", "checkpoint_manifest"], ["alphagpt_pretrain_result.json"]),
    "alphagpt_pretrain_history": _definition("alphagpt_pretrain_history", ["epoch", "loss"], ["alphagpt_pretrain_history.jsonl"], kind="jsonl", allow_empty=True),
    "alphagpt_checkpoint_manifest": _definition("alphagpt_checkpoint_manifest", ["latest_checkpoint_path", "checkpoints"], ["checkpoint_manifest.json"]),
    "model_versions": _definition("model_versions", ["model_version_id", "factor_id", "lifecycle_status"], ["model_versions.jsonl"], kind="jsonl", allow_empty=True),
    "model_deployments": _definition("model_deployments", ["deployment_id", "model_version_id", "status"], ["model_deployments.jsonl"], kind="jsonl", allow_empty=True),
    "lifecycle_events": _definition("lifecycle_events", ["event_id", "model_version_id", "action"], ["lifecycle_events.jsonl"], kind="jsonl", allow_empty=True),
    "model_registry_manifest": _definition("model_registry_manifest", ["model_versions", "deployments", "events"], ["model_registry_manifest.json"]),
    "model_registry_report": _definition("model_registry_report", ["manifest", "active_models", "deployments"], ["model_registry_report.json"]),
    "model_lineage_graph": _definition("model_lineage_graph", ["nodes", "edges"], ["model_lineage_graph.json"]),
    "factor_lifecycle_report": _definition("factor_lifecycle_report", ["evaluation"], ["factor_lifecycle_report.json"]),
    "factor_health_checks": _definition("factor_health_checks", ["name", "severity", "passed"], ["factor_health_checks.jsonl"], kind="jsonl", allow_empty=True),
    "lifecycle_decisions": _definition("lifecycle_decisions", ["factor_id", "recommended_action"], ["lifecycle_decisions.jsonl"], kind="jsonl", allow_empty=True),
    "model_review_package": _definition("model_review_package", ["factor_id", "lifecycle_status", "health_checks"], ["model_review_package.json"]),
    "pit_dataset_contracts": _definition("pit_dataset_contracts", ["datasets"], ["pit_dataset_contracts.json"]),
    "pit_dataset_manifest": _definition("pit_dataset_manifest", ["data_dir", "datasets"], ["pit_dataset_manifest.json"]),
    "pit_validation_report": _definition("pit_validation_report", ["blocker_count", "warning_count", "issues"], ["pit_validation_report.json"]),
    "security_lifecycle": _definition("security_lifecycle", ["ts_code", "list_date", "list_status"], ["security_lifecycle.jsonl"], kind="jsonl", allow_empty=True),
    "active_security_mask": _definition("active_security_mask", ["ts_code", "trade_date", "is_active"], ["active_security_mask.jsonl"], kind="jsonl", allow_empty=True),
    "survivorship_bias_report": _definition("survivorship_bias_report", ["current_only_security_master", "warnings"], ["survivorship_bias_report.json"]),
    "universe_pit_summary": _definition("universe_pit_summary", ["universe_name", "as_of_date"], ["universe_pit_summary.json", "*_pit_summary.json"]),
    "leakage_audit_report": _definition("leakage_audit_report", ["blocker_count", "warning_count", "issues"], ["leakage_audit_report.json"]),
    "leakage_issues": _definition("leakage_issues", ["severity", "code", "message"], ["leakage_issues.jsonl"], kind="jsonl", allow_empty=True),
    "formula_leakage_scan": _definition("formula_leakage_scan", ["scanned_formula_count", "blocked_formula_count"], ["formula_leakage_scan.json"]),
    "truncation_consistency_report": _definition("truncation_consistency_report", ["passed", "max_abs_diff"], ["truncation_consistency_report.json"]),
    "factor_value_leakage_report": _definition("factor_value_leakage_report", ["checked_records", "future_date_count"], ["factor_value_leakage_report.json"]),
    "backtest_leakage_report": _definition("backtest_leakage_report", ["checked", "leakage_gate_status"], ["backtest_leakage_report.json"]),
}


def get_registry() -> dict[str, ArtifactSchemaDefinition]:
    return dict(ARTIFACT_SCHEMA_REGISTRY)


def infer_artifact_type(path: str | Path, registry: dict[str, ArtifactSchemaDefinition] | None = None) -> str | None:
    candidate = Path(path)
    relative = str(candidate).replace("\\", "/")
    name = candidate.name
    for artifact_type, definition in (registry or ARTIFACT_SCHEMA_REGISTRY).items():
        for pattern in definition.file_patterns:
            if fnmatch(name, pattern) or fnmatch(relative, f"*/{pattern}") or fnmatch(relative, pattern):
                return artifact_type
    return None


def get_definition(artifact_type: str | None) -> ArtifactSchemaDefinition | None:
    if artifact_type is None:
        return None
    return ARTIFACT_SCHEMA_REGISTRY.get(artifact_type)
