"""Artifact schema registry for local platform outputs."""

from __future__ import annotations

from fnmatch import fnmatch
from pathlib import Path

from .models import ArtifactSchemaDefinition


def _definition(
    artifact_type: str,
    required: list[str],
    patterns: list[str],
    kind: str = "json",
    optional: list[str] | None = None,
    allow_empty: bool = True,
) -> ArtifactSchemaDefinition:
    return ArtifactSchemaDefinition(
        artifact_type=artifact_type,
        schema_version="1.0",
        required_fields=required,
        optional_fields=optional or [
            "artifact_type",
            "schema_version",
            "producer",
            "created_at",
            "artifact_metadata",
        ],
        file_patterns=patterns,
        json_or_jsonl=kind,
        allow_empty=allow_empty,
    )


ARTIFACT_SCHEMA_REGISTRY: dict[str, ArtifactSchemaDefinition] = {
    "research_suite_result": _definition("research_suite_result", ["suite_name", "status", "stages"], ["suite_result.json"]),
    "artifact_catalog": _definition("artifact_catalog", ["suite_name", "created_at", "entries"], ["artifact_catalog.json"]),
    "promotion_decision": _definition("promotion_decision", [], ["promotion_decision.json"]),
    "data_source_smoke_report": _definition("data_source_smoke_report", ["provider", "status", "datasets"], ["data_source_smoke_report.json"]),
    "provider_probe": _definition("provider_probe", ["probes"], ["provider_probe.json"]),
    "field_coverage": _definition("field_coverage", ["datasets"], ["field_coverage.json"]),
    "audit_summary": _definition("audit_summary", [], ["audit_summary.json"]),
    "incremental_recovery_report": _definition("incremental_recovery_report", [], ["incremental_recovery_report.json"]),
    "baseline_compare_summary": _definition("baseline_compare_summary", [], ["baseline_compare_summary.json"]),
    "dataset_contracts": _definition("dataset_contracts", ["datasets"], ["dataset_contracts.json"]),
    "backfill_plan": _definition("backfill_plan", ["plan_id", "scope", "jobs"], ["backfill_plan.json"]),
    "backfill_state": _definition("backfill_state", ["plan_id", "jobs"], ["backfill_state.json"]),
    "backfill_run_report": _definition("backfill_run_report", ["plan_id", "provider", "status", "jobs"], ["backfill_run_report.json"]),
    "backfill_job_results": _definition("backfill_job_results", ["job_id", "dataset", "status"], ["backfill_job_results.jsonl"], kind="jsonl", allow_empty=True),
    "backfill_job_result": _definition("backfill_job_result", ["job_id", "dataset"], ["job_result.json"]),
    "backfill_staging_records": _definition("backfill_staging_records", [], ["staging/jobs/*/*/records.jsonl"], kind="jsonl", allow_empty=True),
    "backfill_quota_summary": _definition("backfill_quota_summary", ["provider", "status", "estimated_requests"], ["backfill_quota_summary.json"]),
    "backfill_readiness_report": _definition("backfill_readiness_report", ["provider", "status", "quota"], ["backfill_readiness_report.json"]),
    "backfill_coverage_report": _definition("backfill_coverage_report", ["datasets", "gap_count", "status"], ["backfill_coverage_report.json"]),
    "backfill_coverage_matrix": _definition("backfill_coverage_matrix", ["records", "gap_count"], ["backfill_coverage_matrix.json"]),
    "backfill_coverage_gaps": _definition("backfill_coverage_gaps", ["dataset", "gap"], ["backfill_coverage_gaps.jsonl"], kind="jsonl", allow_empty=True),
    "backfill_observer_report": _definition("backfill_observer_report", ["observed_run", "datasets", "eta", "summary"], ["backfill_observer_report.json"]),
    "backfill_dataset_progress": _definition("backfill_dataset_progress", ["dataset", "progress_ratio"], ["backfill_dataset_progress.jsonl"], kind="jsonl", allow_empty=True),
    "backfill_eta_report": _definition("backfill_eta_report", ["remaining_jobs", "confidence"], ["backfill_eta_report.json"]),
    "backfill_repair_plan": _definition("backfill_repair_plan", ["repair_plan_id", "commands"], ["backfill_repair_plan.json"]),
    "backfill_repair_batch_plan": _definition("backfill_repair_batch_plan", ["repair_batch_id", "jobs"], ["repair_batch_plan.json"]),
    "backfill_repair_run_report": _definition("backfill_repair_run_report", ["repair_run_id", "status", "plan", "job_results"], ["repair_run_report.json"]),
    "backfill_repair_job_results": _definition("backfill_repair_job_results", ["repair_job_id", "dataset", "status"], ["repair_job_results.jsonl"], kind="jsonl", allow_empty=True),
    "backfill_repair_events": _definition("backfill_repair_events", ["repair_job_id", "status"], ["repair_events.jsonl"], kind="jsonl", allow_empty=True),
    "backfill_repair_state": _definition("backfill_repair_state", ["repair_batch_id", "jobs"], ["repair_run_state.json"]),
    "backfill_postprocess_plan": _definition("backfill_postprocess_plan", ["plan_id", "steps", "blockers"], ["backfill_postprocess_plan.json"]),
    "backfill_observer_issues": _definition("backfill_observer_issues", ["severity", "code"], ["backfill_observer_issues.jsonl"], kind="jsonl", allow_empty=True),
    "raw_data_landing_report": _definition("raw_data_landing_report", ["data_dir", "datasets", "freeze_readiness", "summary"], ["raw_data_landing_report.json"]),
    "raw_dataset_landing_checks": _definition("raw_dataset_landing_checks", ["dataset", "status"], ["raw_dataset_landing_checks.jsonl"], kind="jsonl", allow_empty=True),
    "raw_dataset_coverage_matrix": _definition("raw_dataset_coverage_matrix", ["datasets", "summary"], ["raw_dataset_coverage_matrix.json"]),
    "raw_freeze_readiness_decision": _definition("raw_freeze_readiness_decision", ["status", "blocker_count", "checks"], ["raw_freeze_readiness_decision.json"]),
    "raw_freeze_readiness_checks": _definition("raw_freeze_readiness_checks", ["dataset", "status"], ["raw_freeze_readiness_checks.jsonl"], kind="jsonl", allow_empty=True),
    "raw_data_index_manifest": _definition("raw_data_index_manifest", ["index_id", "status", "datasets", "index_hash"], ["raw_data_index_manifest.json"]),
    "raw_dataset_indexes": _definition("raw_dataset_indexes", ["dataset", "records_path", "record_count"], ["raw_dataset_indexes.jsonl"], kind="jsonl", allow_empty=True),
    "raw_partitions": _definition("raw_partitions", ["dataset", "partition_key", "partition_type", "record_count"], ["raw_partitions.jsonl"], kind="jsonl", allow_empty=True),
    "raw_data_index_report": _definition("raw_data_index_report", ["status", "data_dir", "summary"], ["raw_data_index_report.json"]),
    "raw_data_index_validation_report": _definition("raw_data_index_validation_report", ["status", "dataset_count", "issues"], ["raw_data_index_validation_report.json"]),
    "raw_data_index_issues": _definition("raw_data_index_issues", ["severity", "code"], ["raw_data_index_issues.jsonl"], kind="jsonl", allow_empty=True),
    "data_quality_lab_report": _definition("data_quality_lab_report", ["status", "scorecard", "freeze_gate", "summary"], ["data_quality_lab_report.json"]),
    "data_quality_scorecard": _definition("data_quality_scorecard", ["status", "dataset_count", "issue_count", "dataset_summaries"], ["data_quality_scorecard.json"]),
    "data_quality_rules": _definition("data_quality_rules", ["rules", "rule_count"], ["data_quality_rules.json"]),
    "data_quality_issues": _definition("data_quality_issues", ["issue_id", "rule_id", "dataset", "severity"], ["data_quality_issues.jsonl"], kind="jsonl", allow_empty=True),
    "dataset_quality_summary": _definition("dataset_quality_summary", ["dataset", "status", "record_count"], ["dataset_quality_summary.jsonl"], kind="jsonl", allow_empty=True),
    "cross_dataset_quality_report": _definition("cross_dataset_quality_report", ["status", "mismatches"], ["cross_dataset_quality_report.json"]),
    "data_quality_repair_suggestions": _definition("data_quality_repair_suggestions", ["suggestion_id", "dataset", "action"], ["data_quality_repair_suggestions.jsonl"], kind="jsonl", allow_empty=True),
    "data_quality_freeze_gate": _definition("data_quality_freeze_gate", ["status", "can_create_freeze", "can_build_matrix"], ["data_quality_freeze_gate.json"]),
    "research_data_readiness_report": _definition("research_data_readiness_report", ["decision", "dataset_checks", "feature_readiness", "summary"], ["research_data_readiness_report.json"]),
    "research_dataset_readiness": _definition("research_dataset_readiness", ["dataset", "tier", "status"], ["research_dataset_readiness.jsonl"], kind="jsonl", allow_empty=True),
    "feature_readiness_catalog": _definition("feature_readiness_catalog", ["feature_families", "summary"], ["feature_readiness_catalog.json"]),
    "research_readiness_decision": _definition("research_readiness_decision", ["status", "core_ready", "alpha_ready"], ["research_readiness_decision.json"]),
    "research_readiness_remediations": _definition("research_readiness_remediations", ["message"], ["research_readiness_remediations.jsonl"], kind="jsonl", allow_empty=True),
    "post_download_plan": _definition("post_download_plan", ["plan_id", "steps", "readiness_status"], ["post_download_plan.json"]),
    "post_download_steps": _definition("post_download_steps", ["step_id", "command"], ["post_download_steps.jsonl"], kind="jsonl", allow_empty=True),
    "post_download_run_report": _definition("post_download_run_report", ["run_id", "mode", "status", "plan"], ["post_download_run_report.json"]),
    "post_download_step_runs": _definition("post_download_step_runs", ["step_id", "status"], ["post_download_step_runs.jsonl"], kind="jsonl", allow_empty=True),
    "post_download_state": _definition("post_download_state", ["run_id", "plan_id", "steps"], ["post_download_state.json"]),
    "post_download_events": _definition("post_download_events", ["step_id", "status"], ["post_download_events.jsonl"], kind="jsonl", allow_empty=True),
    "post_download_final_package": _definition("post_download_final_package", ["status", "run_id"], ["post_download_final_package.json"]),
    "post_download_artifact_catalog": _definition("post_download_artifact_catalog", ["artifact_count", "artifacts"], ["post_download_artifact_catalog.json"]),
    "freeze_candidate_package": _definition("freeze_candidate_package", ["package_id", "status", "data_dir"], ["freeze_candidate_package.json"]),
    "provider_readiness_matrix": _definition("provider_readiness_matrix", ["provider", "status", "rows"], ["provider_readiness_matrix.json"]),
    "api_permission_matrix": _definition("api_permission_matrix", ["rows"], ["api_permission_matrix.json"]),
    "required_dataset_status": _definition("required_dataset_status", ["datasets"], ["required_dataset_status.json"]),
    "real_data_profile": _definition("real_data_profile", ["profile_id", "profile_name", "provider"], ["real_data_profile.json"]),
    "real_data_readiness_report": _definition("real_data_readiness_report", ["status", "provider", "profile_name"], ["real_data_readiness_report.json"]),
    "real_data_pipeline_run": _definition("real_data_pipeline_run", ["run_id", "profile", "status"], ["real_data_pipeline_run.json"]),
    "real_data_pipeline_report": _definition("real_data_pipeline_report", ["run_id", "profile", "status"], ["real_data_pipeline_report.json"]),
    "real_data_runbook": _definition("real_data_runbook", ["profile_name", "resume_command"], ["real_data_runbook.json"]),
    "real_data_sla_report": _definition("real_data_sla_report", ["status", "checks"], ["real_data_sla_report.json"]),
    "real_data_sla_checks": _definition("real_data_sla_checks", ["check_id", "status"], ["real_data_sla_checks.jsonl"], kind="jsonl", allow_empty=True),
    "real_data_size_report": _definition("real_data_size_report", ["data_dir", "total_size_bytes"], ["real_data_size_report.json"]),
    "matrix_refresh_plan": _definition("matrix_refresh_plan", ["refresh_mode", "matrix_cache_dir", "recommendation"], ["matrix_refresh_plan.json"]),
    "matrix_refresh_result": _definition("matrix_refresh_result", ["status", "action", "matrix_cache_dir"], ["matrix_refresh_result.json"]),
    "matrix_source_diff": _definition("matrix_source_diff", ["status", "drift_count"], ["matrix_source_diff.json"]),
    "matrix_freshness_report": _definition("matrix_freshness_report", ["status", "matrix_cache_dir"], ["matrix_freshness_report.json"]),
    "matrix_refresh_issues": _definition("matrix_refresh_issues", ["severity", "code"], ["matrix_refresh_issues.jsonl"], kind="jsonl", allow_empty=True),
    "dataset_version_manifest": _definition("dataset_version_manifest", ["dataset_version_id", "dataset_fingerprints", "content_hash"], ["dataset_version_manifest.json"]),
    "dataset_versions": _definition("dataset_versions", ["dataset_version_id", "content_hash"], ["dataset_versions.jsonl"], kind="jsonl", allow_empty=True),
    "data_lake_registry": _definition("data_lake_registry", ["dataset_versions", "research_freezes"], ["data_lake_registry.json"]),
    "research_data_freeze": _definition("research_data_freeze", ["freeze_id", "dataset_version_id", "content_hash"], ["research_data_freeze.json"]),
    "research_freezes": _definition("research_freezes", ["freeze_id", "dataset_version_id"], ["research_freezes.jsonl"], kind="jsonl", allow_empty=True),
    "freeze_manifest": _definition("freeze_manifest", ["freeze_id", "dataset_version_id", "content_hash", "files"], ["freeze_manifest.json"]),
    "freeze_validation_report": _definition("freeze_validation_report", ["freeze_dir", "status", "error_count"], ["freeze_validation_report.json"]),
    "data_lake_events": _definition("data_lake_events", ["event_type", "target_id"], ["data_lake_events.jsonl"], kind="jsonl", allow_empty=True),
    "data_lake_report": _definition("data_lake_report", ["registry_dir", "versions", "freezes"], ["data_lake_report.json"]),
    "data_lineage_graph": _definition("data_lineage_graph", ["nodes", "edges"], ["data_lineage_graph.json"]),
    "data_retention_report": _definition("data_retention_report", ["freeze_count", "total_size_bytes", "retired_freezes"], ["data_retention_report.json"]),
    "matrix_version_manifest": _definition("matrix_version_manifest", ["fields", "n_stocks", "n_dates"], ["matrix_version_manifest.json"]),
    "feature_set_manifest": _definition("feature_set_manifest", ["feature_set_name", "feature_count", "feature_definitions", "content_hash"], ["feature_set_manifest.json"]),
    "feature_coverage_report": _definition("feature_coverage_report", ["feature_set_name", "feature_count", "feature_summaries"], ["feature_coverage_report.json"]),
    "feature_values_summary": _definition("feature_values_summary", ["feature_set_name", "feature_count", "features"], ["feature_values_summary.json"]),
    "feature_tensor_build_result": _definition("feature_tensor_build_result", ["feature_set_name", "feature_count", "tensor_path"], ["feature_tensor_build_result.json", "feature_factory_report.json"]),
    "feature_family_readiness": _definition("feature_family_readiness", ["feature_set_name", "families", "summary"], ["feature_family_readiness.json"]),
    "feature_pit_alignment_report": _definition("feature_pit_alignment_report", ["feature_set_name", "status", "features"], ["feature_pit_alignment_report.json"]),
    "feature_build_warnings": _definition("feature_build_warnings", ["severity", "code"], ["feature_build_warnings.jsonl"], kind="jsonl", allow_empty=True),
    "feature_promotion_policy": _definition("feature_promotion_policy", ["policy_id", "feature_set_name", "feature_set_hash"], ["feature_promotion_policy.json"]),
    "feature_promotion_evidence": _definition("feature_promotion_evidence", ["feature_name", "pit_contract_status"], ["feature_promotion_evidence.jsonl"], kind="jsonl", allow_empty=True),
    "feature_promotion_evidence_report": _definition("feature_promotion_evidence_report", ["status", "summary"], ["feature_promotion_evidence_report.json"]),
    "feature_promotion_review_package": _definition("feature_promotion_review_package", ["review_id", "summary", "candidates", "evidence"], ["feature_promotion_review_package.json"]),
    "feature_promotion_decisions": _definition("feature_promotion_decisions", ["feature_name", "status"], ["feature_promotion_decisions.jsonl"], kind="jsonl", allow_empty=True),
    "feature_promotion_allowlist": _definition("feature_promotion_allowlist", ["policy_hash", "alpha_eligible_features"], ["feature_promotion_allowlist.json"]),
    "feature_promotion_denylist": _definition("feature_promotion_denylist", ["policy_hash", "blocked_features"], ["feature_promotion_denylist.json"]),
    "feature_promotion_application_report": _definition("feature_promotion_application_report", ["status", "policy_hash", "allowlist_count"], ["feature_promotion_application_report.json"]),
    "alpha_campaign_manifest": _definition("alpha_campaign_manifest", ["campaign_id", "campaign_name", "feature_set_name", "generator_budgets"], ["alpha_campaign_manifest.json"]),
    "alpha_factory_report": _definition("alpha_factory_report", ["campaign_id", "status", "summary"], ["alpha_factory_report.json"]),
    "alpha_generation_stats": _definition("alpha_generation_stats", ["generated", "source_counts"], ["alpha_generation_stats.json"]),
    "alpha_candidates": _definition("alpha_candidates", ["alpha_candidate_id", "formula_hash", "formula_tokens"], ["alpha_candidates.jsonl"], kind="jsonl", allow_empty=True),
    "alpha_static_checks": _definition("alpha_static_checks", ["alpha_candidate_id", "status"], ["alpha_static_checks.jsonl"], kind="jsonl", allow_empty=True),
    "alpha_proxy_eval": _definition("alpha_proxy_eval", ["alpha_candidate_id", "status"], ["alpha_proxy_eval.jsonl"], kind="jsonl", allow_empty=True),
    "alpha_proxy_eval_report": _definition("alpha_proxy_eval_report", ["summary"], ["alpha_proxy_eval_report.json"]),
    "alpha_full_eval_summary": _definition("alpha_full_eval_summary", [], ["alpha_full_eval_summary.json"]),
    "alpha_scored_candidates": _definition("alpha_scored_candidates", ["alpha_candidate_id", "formula_hash", "final_score"], ["alpha_scored_candidates.jsonl"], kind="jsonl", allow_empty=True),
    "alpha_shortlist": _definition("alpha_shortlist", ["alpha_candidate_id", "formula_hash", "final_score"], ["alpha_shortlist.jsonl"], kind="jsonl", allow_empty=True),
    "alpha_rejected": _definition("alpha_rejected", ["alpha_candidate_id", "formula_hash"], ["alpha_rejected.jsonl"], kind="jsonl", allow_empty=True),
    "alpha_diversity_report": _definition("alpha_diversity_report", ["shortlist_count", "family_counts"], ["alpha_diversity_report.json"]),
    "alpha_campaign_artifact_catalog": _definition("alpha_campaign_artifact_catalog", ["campaign_id", "entries"], ["alpha_campaign_artifact_catalog.json"]),
    "alpha_experiment_registry": _definition("alpha_experiment_registry", ["status", "experiment_count", "shard_count"], ["alpha_experiment_registry.json"]),
    "alpha_experiments": _definition("alpha_experiments", ["experiment_id", "campaign_id"], ["alpha_experiments.jsonl"], kind="jsonl", allow_empty=True),
    "alpha_shards": _definition("alpha_shards", ["shard_id", "experiment_id", "shard_index"], ["alpha_shards.jsonl"], kind="jsonl", allow_empty=True),
    "alpha_consolidated_factors": _definition(
        "alpha_consolidated_factors",
        ["consolidated_factor_id", "factor_id", "formula_hash"],
        ["alpha_consolidated_factors.jsonl"],
        kind="jsonl",
        allow_empty=True,
    ),
    "alpha_leaderboard": _definition("alpha_leaderboard", ["rank", "factor_id", "formula_hash", "final_score"], ["alpha_leaderboard.jsonl"], kind="jsonl", allow_empty=True),
    "alpha_experiment_store_report": _definition(
        "alpha_experiment_store_report",
        ["status", "experiment_count", "shard_count", "consolidated_factor_count"],
        ["alpha_experiment_store_report.json"],
    ),
    "alpha_factor_dedup_report": _definition(
        "alpha_factor_dedup_report",
        ["input_shard_count", "input_factor_count", "unique_formula_count", "merged_factor_count"],
        ["alpha_factor_dedup_report.json"],
    ),
    "alpha_campaign_comparison_report": _definition(
        "alpha_campaign_comparison_report",
        ["current_factor_count", "overlap_count", "new_formula_count"],
        ["alpha_campaign_comparison_report.json"],
    ),
    "alpha_validation_candidate_pool": _definition(
        "alpha_validation_candidate_pool",
        ["factor_id", "formula_hash", "rank"],
        ["alpha_validation_candidate_pool.jsonl"],
        kind="jsonl",
        allow_empty=True,
    ),
    "validation_candidate_pool_report": _definition(
        "validation_candidate_pool_report",
        ["candidate_count", "validated_candidate_count"],
        ["validation_candidate_pool_report.json"],
    ),
    "validation_candidate_pool_results": _definition(
        "validation_candidate_pool_results",
        ["factor_id", "status"],
        ["validation_candidate_pool_results.jsonl"],
        kind="jsonl",
        allow_empty=True,
    ),
    "validation_campaign_registry": _definition(
        "validation_campaign_registry",
        ["status", "validation_campaign_count", "candidate_count"],
        ["validation_campaign_registry.json"],
    ),
    "validation_campaigns": _definition(
        "validation_campaigns",
        ["validation_campaign_id", "candidate_count"],
        ["validation_campaigns.jsonl"],
        kind="jsonl",
        allow_empty=True,
    ),
    "validation_candidates": _definition(
        "validation_candidates",
        ["validation_candidate_id", "factor_id", "formula_hash"],
        ["validation_candidates.jsonl"],
        kind="jsonl",
        allow_empty=True,
    ),
    "validation_shards": _definition(
        "validation_shards",
        ["shard_id", "validation_campaign_id", "shard_index", "status"],
        ["validation_shards.jsonl"],
        kind="jsonl",
        allow_empty=True,
    ),
    "validation_candidate_results": _definition(
        "validation_candidate_results",
        ["validation_candidate_id", "factor_id", "validation_status", "validation_score"],
        ["validation_candidate_results.jsonl"],
        kind="jsonl",
        allow_empty=True,
    ),
    "validation_leaderboard": _definition(
        "validation_leaderboard",
        ["rank", "validation_candidate_id", "factor_id", "validation_score"],
        ["validation_leaderboard.jsonl"],
        kind="jsonl",
        allow_empty=True,
    ),
    "factor_certification_queue": _definition(
        "factor_certification_queue",
        ["queue_id", "validation_candidate_id", "factor_id", "priority"],
        ["factor_certification_queue.jsonl"],
        kind="jsonl",
        allow_empty=True,
    ),
    "validation_campaign_store_report": _definition(
        "validation_campaign_store_report",
        ["status", "candidate_count", "shard_count", "result_count"],
        ["validation_campaign_store_report.json"],
    ),
    "factor_materialization_manifest": _definition(
        "factor_materialization_manifest",
        ["factor_id", "materialization_status", "formula_hash", "formula_tokens", "operator_version", "transform_method"],
        ["materialization_manifest.json"],
        optional=["shape", "dtype", "stock_axis_hash", "date_axis_hash", "value_sha256", "validity_sha256", "statistics", "lineage", "input_fingerprint", "blocker"],
    ),
    "engineering_robustness_report": _definition(
        "engineering_robustness_report",
        ["status", "evidence_level", "candidate_count", "materialization_success_count", "validation_blocked_count", "blocker_distribution", "gpu_shards"],
        ["engineering_robustness_report.json"],
    ),
    "clean_holdout_campaign_plan": _definition(
        "clean_holdout_campaign_plan",
        ["status", "research_end_date", "holdout_start_date", "firewall_rule", "start_factor_search"],
        ["clean_holdout_campaign_plan.json"],
    ),
    "feature_validity_manifest": _definition(
        "feature_validity_manifest",
        ["shape", "dtype", "feature_manifest_hash", "validity_sha256", "feature_summaries", "invalid_values_stored_as_zero"],
        ["feature_validity_manifest.json"],
        optional=["artifact_type", "schema_version", "producer", "created_at", "artifact_metadata", "feature_tensor_sha256"],
    ),
    "historical_index_snapshot_proof": _definition(
        "historical_index_snapshot_proof",
        ["index_code", "historical_constituent_proof", "snapshot_count", "snapshot_range", "month_coverage_count", "missing_months", "max_snapshot_gap_days", "union_member_count", "current_member_count", "removed_member_leakage", "stock_axis_hash", "date_axis_hash", "input_fingerprint", "partition_sha256", "blockers"],
        ["snapshot_proof_manifest.json"],
    ),
    "historical_union_members": _definition(
        "historical_union_members",
        ["ts_code"],
        ["historical_union_members.jsonl"],
        kind="jsonl",
        allow_empty=False,
    ),
    "historical_index_snapshots": _definition(
        "historical_index_snapshots",
        ["index_code", "snapshot_date", "ts_code", "weight"],
        ["index_snapshots.jsonl"],
        kind="jsonl",
        allow_empty=False,
    ),
    "task_051_preflight_audit": _definition(
        "task_051_preflight_audit",
        ["status", "source_campaign_id", "raw_data_index_hash", "freeze_hash", "inputs", "suspension_record_count", "dated_suspension_event_count", "unknown_suspension_event_count", "blockers"],
        ["task_051_preflight_audit.json"],
    ),
    "research_observation_ledger": _definition(
        "research_observation_ledger",
        ["campaign_id", "artifact_path", "observed_target_start_date", "max_observed_target_date", "formula_candidate_influenced", "selection_data_reused", "untouched_holdout", "evidence_level"],
        ["research_observation_ledger.jsonl"],
        kind="jsonl",
        allow_empty=True,
    ),
    "future_untouched_holdout_plan": _definition(
        "future_untouched_holdout_plan",
        ["status", "max_observed_target_date", "earliest_holdout_date", "selection_data_reused", "untouched_holdout", "evidence_level", "reason"],
        ["future_untouched_holdout_plan.json"],
    ),
    "targeted_backfill_plan": _definition(
        "targeted_backfill_plan",
        ["status", "default_action", "source_index_hash", "gaps", "credentials_required", "print_credentials"],
        ["targeted_backfill_plan.json"],
    ),
    "task_051_engineering_report": _definition(
        "task_051_engineering_report",
        ["status", "historical_snapshot_proof", "universe_mode", "alpha_discovery_data_ready", "research_holdout_firewall_enabled", "run_twenty_factor_validation", "snapshot_summary", "blockers", "certification_queue_count", "portfolio_queue_count", "paper_deployment_queue_count", "live_deployment_queue_count"],
        ["task_051_engineering_report.json"],
    ),
    "task_052a_accepted_index_snapshots": _definition(
        "task_052a_accepted_index_snapshots",
        ["index_code", "snapshot_date", "effective_trade_date", "ts_code", "weight"],
        ["accepted_index_snapshots.jsonl"],
        kind="jsonl",
        allow_empty=False,
    ),
    "task_052a_universe_proof_manifest": _definition(
        "task_052a_universe_proof_manifest",
        ["generation_id", "content_hash", "semantic_hash", "index_code", "snapshot_count", "rejected_snapshot_count", "member_count", "source_lineage", "membership_lag_trade_days", "removed_member_leakage", "proof_checks", "partition_sha256"],
        ["task_052a_universe_proof_manifest.json"],
    ),
    "task_052a_governed_freeze_manifest": _definition(
        "task_052a_governed_freeze_manifest",
        ["generation_id", "content_hash", "semantic_hash", "source_lineage_manifest_sha256", "artifacts", "immutable", "publication"],
        ["task_052a_governed_freeze_manifest.json"],
    ),
    "task_052a_matrix_readiness_report": _definition(
        "task_052a_matrix_readiness_report",
        ["engineering_matrix_ready", "engineering_blockers", "alpha_discovery_ready", "research_blockers", "readiness_split_enforced"],
        ["task_052a_readiness_report.json"],
    ),
    "task_052a_strict_matrix_manifest": _definition(
        "task_052a_strict_matrix_manifest",
        ["generation_id", "content_hash", "semantic_hash", "shape", "stock_axis_hash", "date_axis_hash", "raw_fields", "validity_masks", "bar_inference_used", "adjustment_factor_fill_value", "membership_lag_trade_days", "target_contract", "readiness", "partition_sha256", "deterministic_build"],
        ["task_052a_strict_matrix_manifest.json"],
    ),
    "task_052_preflight_audit": _definition(
        "task_052_preflight_audit",
        ["status", "raw_index", "freeze", "datasets", "historical_universe", "candidate_pool", "legacy_suspension_status", "proven_root_causes"],
        ["task_052_preflight_audit.json"],
    ),
    "task_052_readiness": _definition(
        "task_052_readiness",
        ["status", "data_foundation_ready", "retrospective_replay_ready", "research_firewall_ready", "feature_family_ready", "untouched_holdout_ready", "certification_ready", "portfolio_ready", "paper_ready", "live_ready", "blockers"],
        ["task_052_readiness.json"],
    ),
    "task_052_backfill_report": _definition(
        "task_052_backfill_report",
        ["status", "union_count", "union_sha256", "observed_end_date", "requests_per_minute", "code_semantic_hash", "datasets", "rate_limit", "token_persisted", "old_sources_mutated"],
        ["task_052_backfill_report.json"],
    ),
    "validation_candidate_dedup_report": _definition(
        "validation_candidate_dedup_report",
        ["validation_campaign_id", "candidate_count", "duplicate_count"],
        ["validation_candidate_dedup_report.json"],
    ),
    "validation_campaign_consolidation_report": _definition(
        "validation_campaign_consolidation_report",
        ["status", "candidate_count", "success_count", "failed_count"],
        ["validation_campaign_consolidation_report.json"],
    ),
    "validation_campaign_comparison_report": _definition(
        "validation_campaign_comparison_report",
        [],
        ["validation_campaign_comparison_report.json"],
    ),
    "validation_campaign_artifact_catalog": _definition(
        "validation_campaign_artifact_catalog",
        ["artifact_count", "artifacts"],
        ["validation_campaign_artifact_catalog.json"],
    ),
    "factor_certification_queue_dry_run": _definition(
        "factor_certification_queue_dry_run",
        ["dry_run", "queue_item_count", "selected_count"],
        ["factor_certification_queue_dry_run.json"],
    ),
    "factor_certification_queue_results": _definition(
        "factor_certification_queue_results",
        ["queue_id", "factor_id"],
        ["factor_certification_queue_results.jsonl"],
        kind="jsonl",
        allow_empty=True,
    ),
    "validation_large_campaign_plan": _definition(
        "validation_large_campaign_plan",
        ["experiment_id", "workflow", "status", "resource_plan"],
        ["validation_large_campaign_plan.json"],
    ),
    "validation_large_campaign_resource_plan": _definition(
        "validation_large_campaign_resource_plan",
        ["workflow", "status", "shard_count"],
        ["validation_large_campaign_resource_plan.json"],
    ),
    "certification_campaign_plan": _definition(
        "certification_campaign_plan",
        ["experiment_id", "workflow", "status", "resource_plan"],
        ["certification_campaign_plan.json"],
    ),
    "portfolio_campaign_plan": _definition(
        "portfolio_campaign_plan",
        ["experiment_id", "workflow", "status", "resource_plan"],
        ["portfolio_campaign_plan.json"],
    ),
    "production_candidate_bundle_plan": _definition(
        "production_candidate_bundle_plan",
        ["experiment_id", "workflow", "status", "resource_plan"],
        ["production_candidate_bundle_plan.json"],
    ),
    "production_candidate_resource_plan": _definition(
        "production_candidate_resource_plan",
        ["workflow", "status"],
        ["resource_plan.json"],
    ),
    "alpha_large_campaign_plan": _definition(
        "alpha_large_campaign_plan",
        ["experiment_id", "workflow", "status", "resource_plan"],
        ["alpha_large_campaign_plan.json"],
    ),
    "alpha_large_campaign_resource_plan": _definition(
        "alpha_large_campaign_resource_plan",
        ["workflow", "status", "shard_count", "gpu_count_requested"],
        ["alpha_large_campaign_resource_plan.json"],
    ),
    "compute_resource_snapshot": _definition("compute_resource_snapshot", ["captured_at", "devices"], ["compute_resource_snapshot.json"]),
    "compute_run_report": _definition("compute_run_report", ["run_id", "status", "job_count"], ["compute_run_report.json"]),
    "compute_jobs": _definition("compute_jobs", ["job_id", "job_kind"], ["compute_jobs.jsonl"], kind="jsonl", allow_empty=True),
    "compute_jobs_manifest": _definition("compute_jobs_manifest", ["jobs"], ["compute_jobs.json"]),
    "compute_job_runs": _definition("compute_job_runs", ["job_id", "status"], ["compute_job_runs.jsonl"], kind="jsonl", allow_empty=True),
    "compute_job_run": _definition("compute_job_run", ["job_id", "status"], ["compute_job_run_*.json"]),
    "compute_scheduler_events": _definition("compute_scheduler_events", ["event_type"], ["compute_scheduler_events.jsonl"], kind="jsonl", allow_empty=True),
    "compute_heartbeats": _definition("compute_heartbeats", ["job_id", "status"], ["compute_heartbeats.jsonl"], kind="jsonl", allow_empty=True),
    "gpu_leases": _definition("gpu_leases", ["lease_id"], ["gpu_leases.jsonl"], kind="jsonl", allow_empty=True),
    "experiment_plan": _definition("experiment_plan", ["experiment_id", "workflow", "compute_jobs"], ["experiment_plan.json"]),
    "experiment_graph": _definition("experiment_graph", ["nodes", "edges"], ["experiment_graph.json"]),
    "experiment_run_report": _definition("experiment_run_report", ["experiment_id", "workflow", "status"], ["experiment_run_report.json"]),
    "experiment_resource_plan": _definition("experiment_resource_plan", ["shard_count"], ["experiment_resource_plan.json"]),
    "experiment_shards": _definition("experiment_shards", ["shard_id", "shard_count"], ["experiment_shards.jsonl"], kind="jsonl", allow_empty=True),
    "experiment_shard_manifest": _definition("experiment_shard_manifest", ["shard_id", "shard_hash"], ["shard_manifest.json"]),
    "experiment_merge_report": _definition("experiment_merge_report", ["status", "shard_count"], ["experiment_merge_report.json"]),
    "experiment_artifact_catalog": _definition("experiment_artifact_catalog", ["experiment_id", "entries"], ["experiment_artifact_catalog.json"]),
    "distributed_training_report": _definition("distributed_training_report", ["distributed", "world_size"], ["distributed_training_report.json"]),
    "resource_usage_report": _definition("resource_usage_report", [], ["resource_usage.json"]),
    "gpu_benchmark_report": _definition("gpu_benchmark_report", [], ["benchmark_result.json", "merged_benchmark_result.json"]),
    "capacity_report": _definition("capacity_report", ["trade_date", "config", "portfolio"], ["capacity_report.json"]),
    "execution_plan": _definition("execution_plan", ["schedule", "fills", "quality"], ["execution_plan.json"]),
    "execution_quality": _definition("execution_quality", ["execution_fill_rate"], ["execution_quality.json"]),
    "parent_orders": _definition("parent_orders", ["parent_order_id"], ["parent_orders.jsonl"], kind="jsonl", allow_empty=True),
    "child_orders": _definition("child_orders", ["child_order_id"], ["child_orders.jsonl"], kind="jsonl", allow_empty=True),
    "child_fills": _definition("child_fills", ["trade_date", "ts_code", "status"], ["child_fills.jsonl"], kind="jsonl", allow_empty=True),
    "broker_report": _definition("broker_report", ["batch_id", "summary"], ["broker_report.json"]),
    "broker_reconciliation": _definition("broker_reconciliation", [], ["broker_reconciliation.json"]),
    "broker_orders": _definition("broker_orders", ["client_order_id"], ["broker_orders.jsonl"], kind="jsonl", allow_empty=True),
    "broker_events": _definition("broker_events", ["event_id"], ["broker_events.jsonl"], kind="jsonl", allow_empty=True),
    "broker_fills": _definition("broker_fills", ["broker_fill_id"], ["broker_fills.jsonl"], kind="jsonl", allow_empty=True),
    "broker_instruction_manifest": _definition("broker_instruction_manifest", ["batch_id"], ["broker_instruction_manifest.json"]),
    "broker_connectivity_profile": _definition("broker_connectivity_profile", ["profile_id", "profile_name", "connectivity_mode"], ["broker_connectivity_profile.json"]),
    "broker_credential_ref_manifest": _definition("broker_credential_ref_manifest", ["profile_id", "credential_refs", "summary"], ["broker_credential_ref_manifest.json"]),
    "broker_network_guard_report": _definition("broker_network_guard_report", ["network_guard"], ["broker_network_guard_report.json"]),
    "broker_connectivity_probe_report": _definition("broker_connectivity_probe_report", ["probe_id", "status", "record_counts"], ["broker_connectivity_probe_report.json"]),
    "broker_connectivity_report": _definition("broker_connectivity_report", ["report_id", "status", "summary"], ["broker_connectivity_report.json"]),
    "broker_connectivity_state": _definition("broker_connectivity_state", ["sessions"], ["broker_connectivity_state.json"]),
    "broker_connectivity_sessions": _definition("broker_connectivity_sessions", ["session_id", "profile_hash", "status"], ["broker_connectivity_sessions.jsonl"], kind="jsonl", allow_empty=True),
    "broker_connectivity_events": _definition("broker_connectivity_events", ["event_id", "event_type"], ["broker_connectivity_events.jsonl"], kind="jsonl", allow_empty=True),
    "broker_connectivity_issues": _definition("broker_connectivity_issues", ["severity", "code", "message"], ["broker_connectivity_issues.jsonl"], kind="jsonl", allow_empty=True),
    "broker_readonly_snapshot": _definition("broker_readonly_snapshot", ["snapshot_id", "status", "cash"], ["broker_readonly_snapshot.json"]),
    "broker_readonly_mirror_report": _definition("broker_readonly_mirror_report", ["report_id", "status", "summary"], ["broker_readonly_mirror_report.json"]),
    "readonly_broker_cash": _definition("readonly_broker_cash", ["account_id"], ["readonly_broker_cash.jsonl"], kind="jsonl", allow_empty=True),
    "readonly_broker_positions": _definition("readonly_broker_positions", ["account_id", "ts_code"], ["readonly_broker_positions.jsonl"], kind="jsonl", allow_empty=True),
    "readonly_broker_orders": _definition("readonly_broker_orders", ["account_id"], ["readonly_broker_orders.jsonl"], kind="jsonl", allow_empty=True),
    "readonly_broker_fills": _definition("readonly_broker_fills", ["account_id"], ["readonly_broker_fills.jsonl"], kind="jsonl", allow_empty=True),
    "readonly_broker_statements": _definition("readonly_broker_statements", ["account_id", "statement_id"], ["readonly_broker_statements.jsonl"], kind="jsonl", allow_empty=True),
    "readonly_mirror_reconciliation_report": _definition("readonly_mirror_reconciliation_report", ["snapshot_id", "status", "break_count"], ["readonly_mirror_reconciliation_report.json"]),
    "readonly_mirror_reconciliation_issues": _definition("readonly_mirror_reconciliation_issues", ["severity", "code", "message"], ["readonly_mirror_reconciliation_issues.jsonl"], kind="jsonl", allow_empty=True),
    "readonly_mirror_state": _definition("readonly_mirror_state", ["snapshots"], ["readonly_mirror_state.json"]),
    "readonly_mirror_snapshots": _definition("readonly_mirror_snapshots", ["snapshot_id", "status"], ["readonly_mirror_snapshots.jsonl"], kind="jsonl", allow_empty=True),
    "readonly_mirror_events": _definition("readonly_mirror_events", ["event_id", "event_type"], ["readonly_mirror_events.jsonl"], kind="jsonl", allow_empty=True),
    "broker_file_gateway_report": _definition("broker_file_gateway_report", ["status", "summary"], ["broker_file_gateway_report.json"]),
    "broker_file_batch": _definition("broker_file_batch", ["file_batch_id", "status"], ["broker_file_batch.json"]),
    "broker_file_manifest": _definition("broker_file_manifest", ["file_batch_id"], ["broker_file_manifest.json", "broker_order_manifest.json"]),
    "broker_file_checksum_manifest": _definition("broker_file_checksum_manifest", ["files"], ["broker_file_checksum_manifest.json"]),
    "broker_file_roundtrip_report": _definition("broker_file_roundtrip_report", ["file_batch_id", "status", "issues"], ["broker_file_roundtrip_report.json"]),
    "broker_file_roundtrip_issues": _definition("broker_file_roundtrip_issues", ["severity", "code", "message"], ["broker_file_roundtrip_issues.jsonl"], kind="jsonl", allow_empty=True),
    "broker_file_events": _definition("broker_file_events", ["event_type", "file_batch_id"], ["broker_file_events.jsonl"], kind="jsonl", allow_empty=True),
    "normalized_broker_file_ack": _definition("normalized_broker_file_ack", ["client_order_id"], ["broker_ack.jsonl", "normalized_broker_file_ack.jsonl"], kind="jsonl", allow_empty=True),
    "normalized_broker_file_status": _definition("normalized_broker_file_status", ["client_order_id", "status"], ["broker_status.jsonl", "normalized_broker_file_status.jsonl"], kind="jsonl", allow_empty=True),
    "normalized_broker_file_fills": _definition("normalized_broker_file_fills", ["client_order_id"], ["broker_fills.jsonl", "normalized_broker_file_fills.jsonl"], kind="jsonl", allow_empty=True),
    "normalized_broker_file_rejects": _definition("normalized_broker_file_rejects", ["client_order_id"], ["broker_rejects.jsonl", "normalized_broker_file_rejects.jsonl"], kind="jsonl", allow_empty=True),
    "operator_handoff_package": _definition("operator_handoff_package", ["handoff_id", "status", "file_batch_id"], ["operator_handoff_package.json", "handoffs/*.json"]),
    "operator_handoff_report": _definition("operator_handoff_report", ["handoff_id", "status", "missing_required_items"], ["operator_handoff_report.json"]),
    "operator_handoff_state": _definition("operator_handoff_state", ["packages"], ["operator_handoff_state.json"]),
    "operator_handoff_events": _definition("operator_handoff_events", ["event", "handoff_id", "status"], ["operator_handoff_events.jsonl"], kind="jsonl", allow_empty=True),
    "operator_handoff_checklist": _definition("operator_handoff_checklist", ["item_id", "status"], ["operator_handoff_checklist.jsonl"], kind="jsonl", allow_empty=True),
    "operator_handoff_evidence": _definition("operator_handoff_evidence", ["evidence_id", "handoff_id"], ["operator_handoff_evidence.jsonl"], kind="jsonl", allow_empty=True),
    "broker_mapping_certification_policy": _definition("broker_mapping_certification_policy", ["policy_name"], ["broker_mapping_certification_policy.json"]),
    "broker_mapping_certification_scorecard": _definition("broker_mapping_certification_scorecard", ["certification_id", "checks"], ["broker_mapping_certification_scorecard.json"]),
    "broker_mapping_certification_decision": _definition("broker_mapping_certification_decision", ["certification_id", "status", "profile_id"], ["broker_mapping_certification_decision.json"]),
    "broker_mapping_certification_package": _definition("broker_mapping_certification_package", ["certification_id", "decision", "policy"], ["broker_mapping_certification_package.json"]),
    "broker_mapping_certification_checks": _definition("broker_mapping_certification_checks", ["check", "value"], ["broker_mapping_certification_checks.jsonl"], kind="jsonl", allow_empty=True),
    "broker_statement_manifest": _definition("broker_statement_manifest", ["statement_id", "account_id", "schema_name", "record_counts"], ["broker_statement_manifest.json"]),
    "broker_statement_import_report": _definition(
        "broker_statement_import_report",
        ["statement_id", "status", "record_counts", "paths"],
        ["broker_statement_import_report.json"],
    ),
    "broker_statement_parse_issues": _definition("broker_statement_parse_issues", ["severity", "code", "message"], ["broker_statement_parse_issues.jsonl"], kind="jsonl", allow_empty=True),
    "broker_statement_validation_report": _definition("broker_statement_validation_report", ["statement_id", "issues"], ["broker_statement_validation_report.json"]),
    "normalized_external_orders": _definition("normalized_external_orders", ["account_id"], ["normalized_external_orders.jsonl"], kind="jsonl", allow_empty=True),
    "normalized_external_trades": _definition("normalized_external_trades", ["account_id"], ["normalized_external_trades.jsonl"], kind="jsonl", allow_empty=True),
    "normalized_external_fills": _definition("normalized_external_fills", ["account_id"], ["normalized_external_fills.jsonl"], kind="jsonl", allow_empty=True),
    "normalized_external_positions": _definition("normalized_external_positions", ["account_id"], ["normalized_external_positions.jsonl"], kind="jsonl", allow_empty=True),
    "normalized_external_cash": _definition("normalized_external_cash", ["account_id"], ["normalized_external_cash.jsonl"], kind="jsonl", allow_empty=True),
    "normalized_external_settlements": _definition("normalized_external_settlements", ["account_id"], ["normalized_external_settlements.jsonl"], kind="jsonl", allow_empty=True),
    "normalized_external_corporate_actions": _definition("normalized_external_corporate_actions", ["account_id"], ["normalized_external_corporate_actions.jsonl"], kind="jsonl", allow_empty=True),
    "eod_reconciliation_report": _definition("eod_reconciliation_report", ["statement_id", "status", "summary"], ["eod_reconciliation_report.json"]),
    "reconciliation_breaks": _definition("reconciliation_breaks", ["break_id", "break_type", "severity"], ["reconciliation_breaks.jsonl"], kind="jsonl", allow_empty=True),
    "external_account_mirror": _definition("external_account_mirror", ["statement_id", "account_id"], ["external_account_mirror.json"]),
    "external_cash_mirror": _definition("external_cash_mirror", ["account_id"], ["external_cash_mirror.jsonl"], kind="jsonl", allow_empty=True),
    "external_position_mirror": _definition("external_position_mirror", ["account_id"], ["external_position_mirror.jsonl"], kind="jsonl", allow_empty=True),
    "external_fill_mirror": _definition("external_fill_mirror", ["account_id"], ["external_fill_mirror.jsonl"], kind="jsonl", allow_empty=True),
    "external_settlement_mirror": _definition("external_settlement_mirror", ["account_id"], ["external_settlement_mirror.jsonl"], kind="jsonl", allow_empty=True),
    "adjustment_proposals": _definition("adjustment_proposals", ["adjustment_id", "adjustment_type"], ["adjustment_proposals.jsonl"], kind="jsonl", allow_empty=True),
    "adjustment_proposal_batch": _definition("adjustment_proposal_batch", ["adjustment_batch_id", "proposals"], ["adjustment_proposal_batch.json"]),
    "adjustment_application_result": _definition("adjustment_application_result", ["approval_id", "applied_count"], ["adjustment_application_result.json"]),
    "adjustment_ledger": _definition("adjustment_ledger", ["adjustment_id", "approval_id"], ["adjustment_ledger.jsonl"], kind="jsonl", allow_empty=True),
    "monitoring_report": _definition("monitoring_report", ["as_of_date", "checks", "alerts"], ["monitoring_report.json"]),
    "alerts": _definition("alerts", ["severity", "check", "message"], ["alerts.jsonl"], kind="jsonl", allow_empty=True),
    "risk_model_report": _definition("risk_model_report", [], ["risk_model_report.json"]),
    "risk_report": _definition("risk_report", [], ["risk_report.json"]),
    "risk_exposures": _definition("risk_exposures", ["trade_date"], ["risk_exposures.jsonl"], kind="jsonl", allow_empty=True),
    "risk_decomposition": _definition("risk_decomposition", ["trade_date"], ["risk_decomposition.jsonl"], kind="jsonl", allow_empty=True),
    "return_attribution": _definition("return_attribution", ["trade_date"], ["return_attribution.jsonl"], kind="jsonl", allow_empty=True),
    "optimization_result": _definition("optimization_result", [], ["optimization_result.json"]),
    "backtest_result": _definition("backtest_result", ["snapshots", "fills", "metrics"], ["backtest_result.json"]),
    "orders": _definition("orders", ["trade_date", "ts_code", "side"], ["orders.jsonl"], kind="jsonl", allow_empty=True),
    "paper_fills": _definition("paper_fills", ["trade_date", "ts_code", "status"], ["paper_fills.jsonl"], kind="jsonl", allow_empty=True),
    "production_run": _definition("production_run", ["run_id", "status", "summary"], ["production_run.json"]),
    "production_orchestrator_report": _definition(
        "production_orchestrator_report",
        ["production_run_id", "trade_date", "run_mode", "status", "summary"],
        ["production_orchestrator_report.json"],
    ),
    "production_run_plan": _definition("production_run_plan", ["production_run_id", "trade_date", "run_mode", "phases"], ["production_run_plan.json"]),
    "production_readiness_report": _definition("production_readiness_report", ["production_run_id", "status", "gates"], ["production_readiness_report.json"]),
    "production_phase_runs": _definition("production_phase_runs", ["production_run_id", "phase", "status"], ["production_phase_runs.jsonl"], kind="jsonl", allow_empty=True),
    "production_gate_results": _definition("production_gate_results", ["gate_id", "status"], ["production_gate_results.jsonl"], kind="jsonl", allow_empty=True),
    "production_run_events": _definition("production_run_events", ["production_run_id"], ["production_run_events.jsonl"], kind="jsonl", allow_empty=True),
    "production_runbook": _definition("production_runbook", ["steps"], ["production_runbook.json"]),
    "production_day_package": _definition("production_day_package", ["production_run_id", "trade_date", "run_mode", "status"], ["production_day_package.json"]),
    "production_runs": _definition("production_runs", ["production_run_id", "status"], ["production_runs.jsonl"], kind="jsonl", allow_empty=True),
    "production_run_state": _definition("production_run_state", ["production_run_id", "status"], ["production_run_state.json"]),
    "production_replay_report": _definition("production_replay_report", ["replay_id", "status", "summary"], ["production_replay_report.json"]),
    "production_replay_plan": _definition("production_replay_plan", ["replay_id", "trade_dates", "day_count"], ["production_replay_plan.json"]),
    "production_replay_days": _definition("production_replay_days", ["replay_id", "trade_date", "status"], ["production_replay_days.jsonl"], kind="jsonl", allow_empty=True),
    "production_replay_events": _definition("production_replay_events", ["replay_id", "event_type", "status"], ["production_replay_events.jsonl"], kind="jsonl", allow_empty=True),
    "production_replay_approvals": _definition("production_replay_approvals", ["replay_id", "trade_date", "approval_id"], ["production_replay_approvals.jsonl"], kind="jsonl", allow_empty=True),
    "production_replay_state": _definition("production_replay_state", ["replay_id", "day_count"], ["production_replay_state.json"]),
    "production_replay_package": _definition("production_replay_package", ["replay_id", "status", "summary"], ["production_replay_package.json"]),
    "production_replay_artifact_catalog": _definition("production_replay_artifact_catalog", ["replay_id", "entries"], ["production_replay_artifact_catalog.json"]),
    "shadow_run_report": _definition("shadow_run_report", ["production_run_id", "trade_date", "status", "summary"], ["shadow_run_report.json"]),
    "shadow_orders": _definition("shadow_orders", ["shadow_order_id", "trade_date", "ts_code"], ["shadow_orders.jsonl"], kind="jsonl", allow_empty=True),
    "shadow_fills": _definition("shadow_fills", ["shadow_fill_id", "trade_date", "ts_code", "status"], ["shadow_fills.jsonl"], kind="jsonl", allow_empty=True),
    "shadow_positions": _definition("shadow_positions", ["ts_code", "shares"], ["shadow_positions.jsonl"], kind="jsonl", allow_empty=True),
    "shadow_account_snapshots": _definition("shadow_account_snapshots", ["trade_date", "equity"], ["shadow_account_snapshots.jsonl"], kind="jsonl", allow_empty=True),
    "shadow_drift_report": _definition("shadow_drift_report", ["production_run_id", "summary"], ["shadow_drift_report.json"]),
    "shadow_performance_report": _definition("shadow_performance_report", ["production_run_id", "trade_date", "metrics"], ["shadow_performance_report.json"]),
    "shadow_vs_production_comparison": _definition("shadow_vs_production_comparison", ["production_run_id", "summary"], ["shadow_vs_production_comparison.json"]),
    "shadow_lab_report": _definition("shadow_lab_report", ["status", "performance_summary", "drift_summary"], ["shadow_lab_report.json"]),
    "shadow_day_summaries": _definition("shadow_day_summaries", ["trade_date", "status"], ["shadow_day_summaries.jsonl"], kind="jsonl", allow_empty=True),
    "shadow_performance_series": _definition("shadow_performance_series", ["trade_date"], ["shadow_performance_series.jsonl"], kind="jsonl", allow_empty=True),
    "shadow_drift_series": _definition("shadow_drift_series", ["trade_date"], ["shadow_drift_series.jsonl"], kind="jsonl", allow_empty=True),
    "shadow_drift_summary": _definition("shadow_drift_summary", ["shadow_target_weight_drift", "shadow_position_weight_drift"], ["shadow_drift_summary.json"]),
    "shadow_calibration_suggestions": _definition("shadow_calibration_suggestions", ["suggestions"], ["shadow_calibration_suggestions.json"]),
    "shadow_lab_issues": _definition("shadow_lab_issues", ["severity", "code", "message"], ["shadow_lab_issues.jsonl"], kind="jsonl", allow_empty=True),
    "live_readiness_policy": _definition("live_readiness_policy", ["policy_id", "profile"], ["live_readiness_policy.json"]),
    "live_readiness_scorecard": _definition("live_readiness_scorecard", ["status", "score", "checks"], ["live_readiness_scorecard.json"]),
    "live_readiness_decision": _definition("live_readiness_decision", ["status", "passed", "new_status"], ["live_readiness_decision.json"]),
    "live_readiness_checks": _definition("live_readiness_checks", ["check_id", "status", "score"], ["live_readiness_checks.jsonl"], kind="jsonl", allow_empty=True),
    "live_readiness_package": _definition("live_readiness_package", ["status", "passed", "score"], ["live_readiness_package.json"]),
    "incident_report": _definition("incident_report", ["incidents", "summary"], ["incident_report.json"]),
    "incident_records": _definition("incident_records", ["incident_id", "status", "severity"], ["incident_records.jsonl"], kind="jsonl", allow_empty=True),
    "incident_events": _definition("incident_events", [], ["incident_events.jsonl"], kind="jsonl", allow_empty=True),
    "incident_runbook": _definition("incident_runbook", ["steps"], ["incident_runbook.json"]),
    "incident_state": _definition("incident_state", [], ["incident_state.json"]),
    "approval_batch": _definition("approval_batch", ["approval_id", "status", "orders"], ["approvals/*.json", "*.approval.json"]),
    "paper_account_state": _definition("paper_account_state", ["account_id", "cash", "positions"], ["account_state.json"]),
    "risk_control_policy_manifest": _definition("risk_control_policy_manifest", ["policy_id", "profile"], ["risk_control_policy_manifest.json", "risk_control_policy.json"]),
    "risk_control_state": _definition("risk_control_state", ["kill_switch"], ["risk_control_state.json"]),
    "risk_control_report": _definition("risk_control_report", ["policy_id", "status", "accepted_orders", "rejected_orders"], ["risk_control_report.json"]),
    "risk_control_breaches": _definition("risk_control_breaches", ["breach_id", "limit_id", "severity"], ["risk_control_breaches.jsonl"], kind="jsonl", allow_empty=True),
    "risk_control_decisions": _definition("risk_control_decisions", ["decision_id", "order_id", "status"], ["risk_control_decisions.jsonl"], kind="jsonl", allow_empty=True),
    "risk_limit_usage": _definition("risk_limit_usage", ["usage_id", "metric", "value"], ["risk_limit_usage.jsonl"], kind="jsonl", allow_empty=True),
    "kill_switch_state": _definition("kill_switch_state", ["active"], ["kill_switch_state.json"]),
    "risk_override_request": _definition("risk_override_request", ["override_id", "scope", "status"], ["risk_override_request.json"]),
    "risk_override_records": _definition("risk_override_records", ["override_id", "approval_id", "status"], ["risk_override_records.jsonl"], kind="jsonl", allow_empty=True),
    "risk_accepted_orders": _definition("risk_accepted_orders", ["trade_date", "ts_code", "side"], ["accepted_orders.jsonl"], kind="jsonl", allow_empty=True),
    "risk_rejected_orders": _definition("risk_rejected_orders", ["trade_date", "ts_code", "side"], ["rejected_orders.jsonl"], kind="jsonl", allow_empty=True),
    "risk_clipped_orders": _definition("risk_clipped_orders", ["trade_date", "ts_code", "side"], ["clipped_orders.jsonl"], kind="jsonl", allow_empty=True),
    "settlement_report": _definition("settlement_report", ["account_id", "as_of_date", "cash_buckets"], ["settlement_report.json"]),
    "settlement_events": _definition("settlement_events", ["settlement_event_id", "account_id", "event_type"], ["settlement_events.jsonl"], kind="jsonl", allow_empty=True),
    "cash_buckets": _definition("cash_buckets", ["trade_date", "total_cash", "available_cash"], ["cash_buckets.jsonl"], kind="jsonl", allow_empty=True),
    "position_lots": _definition("position_lots", ["lot_id", "ts_code", "shares_remaining"], ["position_lots.jsonl"], kind="jsonl", allow_empty=True),
    "position_availability": _definition("position_availability", ["ts_code", "trade_date", "available_shares"], ["position_availability.jsonl"], kind="jsonl", allow_empty=True),
    "realized_pnl": _definition("realized_pnl", ["trade_date", "ts_code", "realized_pnl"], ["realized_pnl.jsonl"], kind="jsonl", allow_empty=True),
    "account_nav": _definition("account_nav", ["trade_date", "equity"], ["account_nav.jsonl"], kind="jsonl", allow_empty=True),
    "account_performance_report": _definition("account_performance_report", [], ["account_performance_report.json"]),
    "account_reconciliation_report": _definition("account_reconciliation_report", ["account_id", "as_of_date"], ["account_reconciliation_report.json"]),
    "fee_tax_report": _definition("fee_tax_report", [], ["fee_tax_report.json"]),
    "corporate_actions_report": _definition("corporate_actions_report", ["event_count", "implemented_action_count"], ["corporate_actions_report.json"]),
    "corporate_action_events": _definition("corporate_action_events", ["action_id", "ts_code", "action_type"], ["corporate_action_events.jsonl"], kind="jsonl", allow_empty=True),
    "corporate_action_schedule": _definition("corporate_action_schedule", ["schedule"], ["corporate_action_schedule.json"]),
    "corporate_action_validation_report": _definition("corporate_action_validation_report", ["event_count", "issues"], ["corporate_action_validation_report.json"]),
    "adjustment_factor_reconciliation": _definition("adjustment_factor_reconciliation", ["issue_count", "issues"], ["adjustment_factor_reconciliation.json"]),
    "total_return_series": _definition("total_return_series", ["trade_date", "ts_code", "total_return_price"], ["total_return_series.jsonl"], kind="jsonl", allow_empty=True),
    "total_return_report": _definition("total_return_report", ["records", "total_return_mode"], ["total_return_report.json"]),
    "corporate_action_ledger": _definition("corporate_action_ledger", ["action_id", "status"], ["corporate_action_ledger.jsonl"], kind="jsonl", allow_empty=True),
    "settlement_ledger": _definition("settlement_ledger", [], ["settlement_ledger.jsonl"], kind="jsonl", allow_empty=True),
    "artifact_schema_manifest": _definition("artifact_schema_manifest", ["entries"], ["artifact_schema_manifest.json"]),
    "artifact_validation_report": _definition("artifact_validation_report", ["results"], ["artifact_validation_report.json"]),
    "release_manifest": _definition("release_manifest", ["release_name", "created_at"], ["release_manifest.json"]),
    "release_gate_report": _definition("release_gate_report", ["checks"], ["release_gate_report.json"]),
    "dependency_inventory": _definition("dependency_inventory", ["files"], ["dependency_inventory.json"]),
    "module_inventory": _definition("module_inventory", ["modules"], ["module_inventory.json"]),
    "cli_inventory": _definition("cli_inventory", ["entries"], ["cli_inventory.json"]),
    "ci_report": _definition("ci_report", ["commands"], ["ci_report.json"]),
    "ci_command_results": _definition("ci_command_results", ["name", "returncode"], ["ci_command_results.jsonl"], kind="jsonl", allow_empty=True),
    "formula_corpus": _definition("formula_corpus", ["formula_hash", "formula_tokens"], ["formula_corpus.jsonl"], kind="jsonl", allow_empty=False),
    "formula_sequences": _definition("formula_sequences", ["formula_hash", "prefix_tokens", "target_token"], ["formula_sequences.jsonl"], kind="jsonl", allow_empty=False),
    "formula_preferences": _definition("formula_preferences", ["pair_id", "preferred_hash", "rejected_hash"], ["formula_preferences.jsonl"], kind="jsonl", allow_empty=True),
    "formula_corpus_stats": _definition("formula_corpus_stats", ["total_records", "valid_records"], ["formula_corpus_stats.json"]),
    "formula_corpus_build_result": _definition("formula_corpus_build_result", ["created_at", "stats", "paths"], ["formula_corpus_build_result.json"]),
    "formula_batch_eval_result": _definition("formula_batch_eval_result", ["batch_id", "results", "summary"], ["formula_batch_eval_result.json"]),
    "formula_eval_results": _definition("formula_eval_results", ["request", "status", "score"], ["formula_eval_results.jsonl"], kind="jsonl", allow_empty=True),
    "formula_eval_cache_manifest": _definition("formula_eval_cache_manifest", ["cache_dir", "enabled"], ["formula_eval_cache_manifest.json"]),
    "formula_batch_eval_benchmark": _definition("formula_batch_eval_benchmark", ["formulas_requested", "elapsed_seconds"], ["formula_batch_eval_benchmark.json"]),
    "formula_eval_shard_manifest": _definition("formula_eval_shard_manifest", ["shard_id", "shard_count", "record_count"], ["shard_manifest.json"]),
    "alphagpt_pretrain_result": _definition("alphagpt_pretrain_result", ["status", "history", "checkpoint_manifest"], ["alphagpt_pretrain_result.json"]),
    "alphagpt_pretrain_history": _definition("alphagpt_pretrain_history", ["epoch", "loss"], ["alphagpt_pretrain_history.jsonl"], kind="jsonl", allow_empty=True),
    "alphagpt_checkpoint_manifest": _definition("alphagpt_checkpoint_manifest", ["latest_checkpoint_path", "checkpoints"], ["checkpoint_manifest.json"]),
    "model_versions": _definition("model_versions", ["model_version_id", "factor_id", "lifecycle_status"], ["model_versions.jsonl"], kind="jsonl", allow_empty=True),
    "model_deployments": _definition("model_deployments", ["deployment_id", "model_version_id", "status"], ["model_deployments.jsonl"], kind="jsonl", allow_empty=True),
    "lifecycle_events": _definition("lifecycle_events", ["event_id", "model_version_id", "action"], ["lifecycle_events.jsonl"], kind="jsonl", allow_empty=True),
    "model_registry_manifest": _definition("model_registry_manifest", ["model_versions", "deployments", "events"], ["model_registry_manifest.json"]),
    "model_registry_report": _definition("model_registry_report", ["manifest", "active_models", "deployments"], ["model_registry_report.json"]),
    "model_lineage_graph": _definition("model_lineage_graph", ["nodes", "edges"], ["model_lineage_graph.json"]),
    "factor_lifecycle_report": _definition("factor_lifecycle_report", ["evaluation"], ["factor_lifecycle_report.json"]),
    "factor_health_checks": _definition("factor_health_checks", ["name", "severity", "passed"], ["factor_health_checks.jsonl"], kind="jsonl", allow_empty=True),
    "lifecycle_decisions": _definition("lifecycle_decisions", ["factor_id", "recommended_action"], ["lifecycle_decisions.jsonl"], kind="jsonl", allow_empty=True),
    "model_review_package": _definition("model_review_package", ["factor_id", "lifecycle_status", "health_checks"], ["model_review_package.json"]),
    "pit_dataset_contracts": _definition("pit_dataset_contracts", ["datasets"], ["pit_dataset_contracts.json"]),
    "pit_dataset_manifest": _definition("pit_dataset_manifest", ["data_dir", "datasets"], ["pit_dataset_manifest.json"]),
    "pit_validation_report": _definition("pit_validation_report", ["blocker_count", "warning_count", "issues"], ["pit_validation_report.json"]),
    "security_lifecycle": _definition("security_lifecycle", ["ts_code", "list_date", "list_status"], ["security_lifecycle.jsonl"], kind="jsonl", allow_empty=True),
    "active_security_mask": _definition("active_security_mask", ["ts_code", "trade_date", "is_active"], ["active_security_mask.jsonl"], kind="jsonl", allow_empty=True),
    "survivorship_bias_report": _definition("survivorship_bias_report", ["current_only_security_master", "warnings"], ["survivorship_bias_report.json"]),
    "universe_pit_summary": _definition("universe_pit_summary", ["universe_name", "as_of_date"], ["universe_pit_summary.json", "*_pit_summary.json"]),
    "leakage_audit_report": _definition("leakage_audit_report", ["blocker_count", "warning_count", "issues"], ["leakage_audit_report.json"]),
    "leakage_issues": _definition("leakage_issues", ["severity", "code", "message"], ["leakage_issues.jsonl"], kind="jsonl", allow_empty=True),
    "formula_leakage_scan": _definition("formula_leakage_scan", ["scanned_formula_count", "blocked_formula_count"], ["formula_leakage_scan.json"]),
    "truncation_consistency_report": _definition("truncation_consistency_report", ["passed", "max_abs_diff"], ["truncation_consistency_report.json"]),
    "factor_value_leakage_report": _definition("factor_value_leakage_report", ["checked_records", "future_date_count"], ["factor_value_leakage_report.json"]),
    "backtest_leakage_report": _definition("backtest_leakage_report", ["checked", "leakage_gate_status"], ["backtest_leakage_report.json"]),
    "validation_lab_report": _definition("validation_lab_report", ["target", "validation_summary", "status"], ["validation_lab_report.json"]),
    "validation_splits": _definition("validation_splits", ["split_id", "method"], ["validation_splits.jsonl"], kind="jsonl", allow_empty=True),
    "factor_validation_results": _definition("factor_validation_results", ["split_id", "test_metrics"], ["factor_validation_results.jsonl"], kind="jsonl", allow_empty=True),
    "factor_validation_summary": _definition("factor_validation_summary", ["factor_id", "out_of_sample_score", "window_pass_ratio"], ["factor_validation_summary.json"]),
    "multiple_testing_report": _definition("multiple_testing_report", ["total_trials", "effective_trial_count"], ["multiple_testing_report.json"]),
    "overfit_risk_report": _definition("overfit_risk_report", ["pbo_estimate", "deflated_ic_like_score"], ["overfit_risk_report.json"]),
    "placebo_test_report": _definition("placebo_test_report", [], ["placebo_test_report.json"]),
    "placebo_trials": _definition("placebo_trials", ["trial", "mode", "score"], ["placebo_trials.jsonl"], kind="jsonl", allow_empty=True),
    "regime_validation_report": _definition("regime_validation_report", ["regime_count", "regime_pass_ratio"], ["regime_validation_report.json"]),
    "regime_results": _definition("regime_results", ["regime_name", "metrics"], ["regime_results.jsonl"], kind="jsonl", allow_empty=True),
    "sensitivity_report": _definition("sensitivity_report", ["scenario_count", "sensitivity_pass_ratio"], ["sensitivity_report.json"]),
    "sensitivity_results": _definition("sensitivity_results", ["scenario_id", "parameters", "metrics"], ["sensitivity_results.jsonl"], kind="jsonl", allow_empty=True),
    "robustness_surface": _definition("robustness_surface", ["scenario_count"], ["robustness_surface.json"]),
    "stress_backtest_report": _definition("stress_backtest_report", ["stress_scenario_count", "stress_backtest_pass_ratio"], ["stress_backtest_report.json"]),
    "stress_backtest_results": _definition("stress_backtest_results", ["scenario_id", "parameters", "metrics"], ["stress_backtest_results.jsonl"], kind="jsonl", allow_empty=True),
    "validation_issues": _definition("validation_issues", ["severity", "code", "message"], ["validation_issues.jsonl"], kind="jsonl", allow_empty=True),
    "factor_certification_policy": _definition("factor_certification_policy", ["policy_id", "profile_name"], ["factor_certification_policy.json"]),
    "factor_certification_scorecard": _definition("factor_certification_scorecard", ["factor_id", "checks", "summary"], ["factor_certification_scorecard.json"]),
    "factor_certification_decision": _definition("factor_certification_decision", ["factor_id", "status", "passed"], ["factor_certification_decision.json"]),
    "factor_certification_package": _definition("factor_certification_package", ["factor_id", "policy", "scorecard", "decision"], ["factor_certification_package.json"]),
    "factor_certification_checks": _definition("factor_certification_checks", ["name", "status", "severity"], ["factor_certification_checks.jsonl"], kind="jsonl", allow_empty=True),
    "factor_certification_campaign_registry": _definition(
        "factor_certification_campaign_registry",
        ["status", "campaign_count", "item_count"],
        ["factor_certification_campaign_registry.json"],
    ),
    "factor_certification_campaigns": _definition(
        "factor_certification_campaigns",
        ["certification_campaign_id", "candidate_count"],
        ["factor_certification_campaigns.jsonl"],
        kind="jsonl",
        allow_empty=True,
    ),
    "factor_certification_items": _definition(
        "factor_certification_items",
        ["item_id", "queue_id", "factor_id", "status"],
        ["factor_certification_items.jsonl"],
        kind="jsonl",
        allow_empty=True,
    ),
    "factor_certification_campaign_report": _definition(
        "factor_certification_campaign_report",
        ["status", "item_count", "certified_factor_pool_count"],
        ["factor_certification_campaign_report.json"],
    ),
    "factor_certification_campaign_ingest_report": _definition(
        "factor_certification_campaign_ingest_report",
        ["status", "certification_campaign_id", "item_count"],
        ["factor_certification_campaign_ingest_report.json"],
    ),
    "factor_certification_campaign_consolidation_report": _definition(
        "factor_certification_campaign_consolidation_report",
        ["status", "item_count", "certified_factor_pool_count"],
        ["factor_certification_campaign_consolidation_report.json"],
    ),
    "certified_factor_pool": _definition(
        "certified_factor_pool",
        ["certified_factor_pool_id", "factor_id", "certification_status"],
        ["certified_factor_pool.jsonl"],
        kind="jsonl",
        allow_empty=True,
    ),
    "certified_factor_leaderboard": _definition(
        "certified_factor_leaderboard",
        ["rank", "certified_factor_pool_id", "factor_id", "certification_score"],
        ["certified_factor_leaderboard.jsonl"],
        kind="jsonl",
        allow_empty=True,
    ),
    "factor_certification_campaign_artifact_catalog": _definition(
        "factor_certification_campaign_artifact_catalog",
        ["artifact_count", "artifacts"],
        ["factor_certification_campaign_artifact_catalog.json"],
    ),
    "portfolio_policy": _definition("portfolio_policy", ["policy_id", "portfolio_method"], ["portfolio_policy.json"]),
    "portfolio_policy_grid": _definition("portfolio_policy_grid", ["policies"], ["portfolio_policy_grid.json"]),
    "portfolio_scenarios": _definition("portfolio_scenarios", ["scenarios"], ["portfolio_scenarios.json"]),
    "portfolio_lab_report": _definition("portfolio_lab_report", ["lab_id", "status", "factor_id", "summary"], ["portfolio_lab_report.json"]),
    "portfolio_policy_trials": _definition("portfolio_policy_trials", ["trial_id", "policy_id", "scenario_id"], ["portfolio_policy_trials.jsonl"], kind="jsonl", allow_empty=True),
    "portfolio_trial_metrics": _definition("portfolio_trial_metrics", ["trial_id", "policy_id", "score"], ["portfolio_trial_metrics.jsonl"], kind="jsonl", allow_empty=True),
    "portfolio_robustness_report": _definition("portfolio_robustness_report", ["ranked_policies"], ["portfolio_robustness_report.json"]),
    "selected_portfolio_policy": _definition("selected_portfolio_policy", ["policy_id", "portfolio_method"], ["selected_portfolio_policy.json"]),
    "portfolio_lab_issues": _definition("portfolio_lab_issues", ["severity", "code", "message"], ["portfolio_lab_issues.jsonl"], kind="jsonl", allow_empty=True),
    "portfolio_lab_artifact_catalog": _definition("portfolio_lab_artifact_catalog", ["entries"], ["portfolio_lab_artifact_catalog.json"]),
    "portfolio_certification_policy": _definition("portfolio_certification_policy", ["policy_id", "profile_name"], ["portfolio_certification_policy.json"]),
    "portfolio_certification_scorecard": _definition("portfolio_certification_scorecard", ["portfolio_policy_id", "checks", "summary"], ["portfolio_certification_scorecard.json"]),
    "portfolio_certification_decision": _definition("portfolio_certification_decision", ["portfolio_policy_id", "status", "passed"], ["portfolio_certification_decision.json"]),
    "portfolio_certification_package": _definition("portfolio_certification_package", ["portfolio_policy_id", "portfolio_policy", "scorecard", "decision"], ["portfolio_certification_package.json"]),
    "portfolio_certification_checks": _definition("portfolio_certification_checks", ["name", "status", "severity"], ["portfolio_certification_checks.jsonl"], kind="jsonl", allow_empty=True),
    "certified_portfolio_policy": _definition("certified_portfolio_policy", ["policy_id", "portfolio_method", "certification_status"], ["certified_portfolio_policy.json"]),
    "portfolio_policy_activation_request": _definition("portfolio_policy_activation_request", ["portfolio_policy_id", "requested_action"], ["portfolio_policy_activation_request.json"]),
    "portfolio_certification_campaign_registry": _definition(
        "portfolio_certification_campaign_registry",
        ["status", "campaign_count", "item_count"],
        ["portfolio_certification_campaign_registry.json"],
    ),
    "portfolio_certification_campaigns": _definition(
        "portfolio_certification_campaigns",
        ["portfolio_campaign_id", "factor_count"],
        ["portfolio_certification_campaigns.jsonl"],
        kind="jsonl",
        allow_empty=True,
    ),
    "portfolio_candidate_items": _definition(
        "portfolio_candidate_items",
        ["item_id", "factor_id", "status"],
        ["portfolio_candidate_items.jsonl"],
        kind="jsonl",
        allow_empty=True,
    ),
    "portfolio_certification_campaign_report": _definition(
        "portfolio_certification_campaign_report",
        ["status", "item_count", "production_candidate_bundle_count"],
        ["portfolio_certification_campaign_report.json"],
    ),
    "portfolio_campaign_ingest_report": _definition(
        "portfolio_campaign_ingest_report",
        ["status", "portfolio_campaign_id", "item_count"],
        ["portfolio_campaign_ingest_report.json"],
    ),
    "production_candidate_bundle": _definition(
        "production_candidate_bundle",
        ["production_candidate_bundle_id", "factor_id", "portfolio_certification_status"],
        ["production_candidate_bundle.jsonl"],
        kind="jsonl",
        allow_empty=True,
    ),
    "production_candidate_bundle_report": _definition(
        "production_candidate_bundle_report",
        ["status", "production_candidate_bundle_count", "optimizer_policy_activation_queue_count"],
        ["production_candidate_bundle_report.json"],
    ),
    "optimizer_policy_activation_queue": _definition(
        "optimizer_policy_activation_queue",
        ["activation_queue_id", "factor_id", "status"],
        ["optimizer_policy_activation_queue.jsonl"],
        kind="jsonl",
        allow_empty=True,
    ),
    "portfolio_campaign_artifact_catalog": _definition(
        "portfolio_campaign_artifact_catalog",
        ["artifact_count", "artifacts"],
        ["portfolio_campaign_artifact_catalog.json"],
    ),
    "program_trading_system_inventory": _definition("program_trading_system_inventory", ["inventory_id", "real_broker_submit_supported"], ["program_trading_system_inventory.json"]),
    "program_trading_strategy_inventory": _definition("program_trading_strategy_inventory", [], ["program_trading_strategy_inventory.json"]),
    "program_trading_risk_control_inventory": _definition("program_trading_risk_control_inventory", ["kill_switch_available"], ["program_trading_risk_control_inventory.json"]),
    "program_trading_compliance_pack": _definition("program_trading_compliance_pack", ["compliance_pack_id", "status", "summary"], ["program_trading_compliance_pack.json"]),
    "program_trading_evidence_records": _definition("program_trading_evidence_records", ["evidence_id", "category", "status"], ["program_trading_evidence_records.jsonl"], kind="jsonl", allow_empty=True),
    "program_trading_compliance_checklist": _definition("program_trading_compliance_checklist", ["item_id", "status"], ["program_trading_compliance_checklist.jsonl"], kind="jsonl", allow_empty=True),
    "compliance_gap_report": _definition("compliance_gap_report", ["gap_count", "status"], ["compliance_gap_report.json"]),
    "secret_scan_report": _definition("secret_scan_report", ["finding_count", "blocker_count", "status"], ["secret_scan_report.json"]),
    "secret_scan_findings": _definition("secret_scan_findings", ["path", "severity", "code"], ["secret_scan_findings.jsonl"], kind="jsonl", allow_empty=True),
    "compliance_review_package": _definition("compliance_review_package", ["review_id", "compliance_pack_path", "status"], ["compliance_review_package.json"]),
    "broker_uat_plan": _definition("broker_uat_plan", ["plan_id", "scenarios"], ["broker_uat_plan.json"]),
    "broker_uat_report": _definition("broker_uat_report", ["uat_id", "status", "summary"], ["broker_uat_report.json"]),
    "broker_uat_scenarios": _definition("broker_uat_scenarios", ["scenario_id", "scenario_type"], ["broker_uat_scenarios.jsonl"], kind="jsonl", allow_empty=True),
    "broker_uat_results": _definition("broker_uat_results", ["scenario_id", "status"], ["broker_uat_results.jsonl"], kind="jsonl", allow_empty=True),
    "broker_adapter_capability_manifest": _definition("broker_adapter_capability_manifest", ["adapter_name", "real_network_required", "real_broker_credentials_required"], ["broker_adapter_capability_manifest.json"]),
    "broker_adapter_contract_report": _definition("broker_adapter_contract_report", ["adapter_name", "status", "scenario_count"], ["broker_adapter_contract_report.json"]),
    "broker_uat_replay_report": _definition("broker_uat_replay_report", ["status"], ["broker_uat_replay_report.json"]),
    "broker_uat_issues": _definition("broker_uat_issues", ["severity", "code", "message"], ["broker_uat_issues.jsonl"], kind="jsonl", allow_empty=True),
    "go_live_gate_policy": _definition("go_live_gate_policy", ["policy_id", "profile_name"], ["go_live_gate_policy.json"]),
    "go_live_gate_scorecard": _definition("go_live_gate_scorecard", ["status", "checks", "summary"], ["go_live_gate_scorecard.json"]),
    "go_live_gate_decision": _definition("go_live_gate_decision", ["status", "passed", "required_remediation"], ["go_live_gate_decision.json"]),
    "go_live_gate_checks": _definition("go_live_gate_checks", ["check_id", "status", "severity"], ["go_live_gate_checks.jsonl"], kind="jsonl", allow_empty=True),
    "go_live_review_package": _definition("go_live_review_package", ["review_id", "go_live_status", "status"], ["go_live_review_package.json"]),
}


def get_registry() -> dict[str, ArtifactSchemaDefinition]:
    return dict(ARTIFACT_SCHEMA_REGISTRY)


def infer_artifact_type(path: str | Path, registry: dict[str, ArtifactSchemaDefinition] | None = None) -> str | None:
    candidate = Path(path)
    relative = str(candidate).replace("\\", "/")
    name = candidate.name
    for artifact_type, definition in (registry or ARTIFACT_SCHEMA_REGISTRY).items():
        for pattern in definition.file_patterns:
            if fnmatch(name, pattern) or fnmatch(relative, f"*/{pattern}") or fnmatch(relative, pattern):
                return artifact_type
    return None


def get_definition(artifact_type: str | None) -> ArtifactSchemaDefinition | None:
    if artifact_type is None:
        return None
    return ARTIFACT_SCHEMA_REGISTRY.get(artifact_type)
