"""Point-in-time availability contracts for local A-share datasets."""

from __future__ import annotations

from .models import DatasetAvailabilityTiming, PITDatasetContract


PIT_DATASET_CONTRACTS: dict[str, PITDatasetContract] = {
    "securities": PITDatasetContract(
        dataset="securities",
        date_field="list_date",
        entity_field="ts_code",
        availability_date_field="list_date",
        effective_date_field="list_date",
        required_fields=["ts_code", "symbol", "name", "exchange", "list_date", "list_status", "delist_date"],
        max_allowed_lag_days=None,
        timing=DatasetAvailabilityTiming.effective_date,
        allow_forward_fill=True,
        point_in_time_safe_by_default=False,
        notes="Security lifecycle depends on historical list_status/delist_date coverage.",
    ),
    "trade_calendar": PITDatasetContract(
        dataset="trade_calendar",
        date_field="trade_date",
        entity_field=None,
        availability_date_field="trade_date",
        effective_date_field="trade_date",
        required_fields=["trade_date", "is_open"],
        max_allowed_lag_days=None,
        timing=DatasetAvailabilityTiming.before_market_open,
        allow_forward_fill=False,
        point_in_time_safe_by_default=True,
    ),
    "daily_bars": PITDatasetContract(
        dataset="daily_bars",
        date_field="trade_date",
        entity_field="ts_code",
        availability_date_field="trade_date",
        effective_date_field="trade_date",
        required_fields=["trade_date", "ts_code", "open", "high", "low", "close", "pre_close", "volume", "amount"],
        max_allowed_lag_days=1,
        timing=DatasetAvailabilityTiming.after_market_close,
        allow_forward_fill=False,
        point_in_time_safe_by_default=False,
        notes="Same-day close/amount are available only after the close.",
    ),
    "daily_basic": PITDatasetContract(
        dataset="daily_basic",
        date_field="trade_date",
        entity_field="ts_code",
        availability_date_field="trade_date",
        effective_date_field="trade_date",
        required_fields=["trade_date", "ts_code", "turnover_rate", "pe_ttm", "pb", "total_mv"],
        max_allowed_lag_days=1,
        timing=DatasetAvailabilityTiming.after_market_close,
        allow_forward_fill=True,
        point_in_time_safe_by_default=False,
    ),
    "financial_features": PITDatasetContract(
        dataset="financial_features",
        date_field="report_period",
        entity_field="ts_code",
        availability_date_field="announce_date",
        effective_date_field="report_period",
        required_fields=["ts_code", "report_period", "announce_date"],
        max_allowed_lag_days=None,
        timing=DatasetAvailabilityTiming.announced_date,
        allow_forward_fill=True,
        point_in_time_safe_by_default=True,
    ),
    "daily_limits": PITDatasetContract(
        dataset="daily_limits",
        date_field="trade_date",
        entity_field="ts_code",
        availability_date_field="trade_date",
        effective_date_field="trade_date",
        required_fields=["trade_date", "ts_code", "up_limit", "down_limit", "pre_close"],
        max_allowed_lag_days=1,
        timing=DatasetAvailabilityTiming.after_market_close,
        allow_forward_fill=False,
        point_in_time_safe_by_default=False,
    ),
    "adjustment_factors": PITDatasetContract(
        dataset="adjustment_factors",
        date_field="trade_date",
        entity_field="ts_code",
        availability_date_field="trade_date",
        effective_date_field="trade_date",
        required_fields=["trade_date", "ts_code", "adj_factor"],
        max_allowed_lag_days=None,
        timing=DatasetAvailabilityTiming.unknown,
        allow_forward_fill=True,
        point_in_time_safe_by_default=False,
        notes="Adjustment factors may be restated and require policy review.",
    ),
    "index_members": PITDatasetContract(
        dataset="index_members",
        date_field="trade_date",
        entity_field="ts_code",
        availability_date_field="trade_date",
        effective_date_field="trade_date",
        required_fields=["index_code", "trade_date", "ts_code", "weight"],
        max_allowed_lag_days=None,
        timing=DatasetAvailabilityTiming.effective_date,
        allow_forward_fill=True,
        point_in_time_safe_by_default=False,
        notes="Index weights may have publication delays and require manual review.",
    ),
    "corporate_actions": PITDatasetContract(
        dataset="corporate_actions",
        date_field="ex_date",
        entity_field="ts_code",
        availability_date_field="imp_ann_date",
        effective_date_field="ex_date",
        required_fields=["ts_code", "ann_date", "div_proc", "record_date", "ex_date", "pay_date"],
        max_allowed_lag_days=None,
        timing=DatasetAvailabilityTiming.announced_date,
        allow_forward_fill=False,
        point_in_time_safe_by_default=False,
        notes="ann_date/imp_ann_date controls availability, ex_date controls price/share effects, pay_date controls cash receipt.",
    ),
    "universe": PITDatasetContract(
        dataset="universe",
        date_field="as_of_date",
        entity_field="ts_code",
        availability_date_field="as_of_date",
        effective_date_field="as_of_date",
        required_fields=["ts_code"],
        max_allowed_lag_days=None,
        timing=DatasetAvailabilityTiming.effective_date,
        allow_forward_fill=False,
        point_in_time_safe_by_default=False,
    ),
    "factor_values": PITDatasetContract(
        dataset="factor_values",
        date_field="trade_date",
        entity_field="ts_code",
        availability_date_field="trade_date",
        effective_date_field="trade_date",
        required_fields=["factor_id", "trade_date", "ts_code", "value"],
        max_allowed_lag_days=None,
        timing=DatasetAvailabilityTiming.after_market_close,
        allow_forward_fill=False,
        point_in_time_safe_by_default=False,
    ),
    "backtest_inputs": PITDatasetContract(
        dataset="backtest_inputs",
        date_field="trade_date",
        entity_field="ts_code",
        availability_date_field="signal_date",
        effective_date_field="trade_date",
        required_fields=["trade_date", "ts_code"],
        max_allowed_lag_days=None,
        timing=DatasetAvailabilityTiming.unknown,
        allow_forward_fill=False,
        point_in_time_safe_by_default=False,
    ),
}


def contracts_for_datasets(datasets: list[str] | None = None) -> dict[str, PITDatasetContract]:
    if datasets is None:
        return dict(PIT_DATASET_CONTRACTS)
    return {dataset: PIT_DATASET_CONTRACTS[dataset] for dataset in datasets if dataset in PIT_DATASET_CONTRACTS}
